# -*- coding: utf-8 -*-
"""Banque Cameroun : economie, agriculture, ressources et vie des affaires."""

from __future__ import annotations

from .common import CHALLENGE, FACILE, MOYEN, Q, others

ZONES = ["Le Grand Nord", "L'Ouest et le Nord-Ouest", "Le Littoral et le Sud-Ouest",
         "Le Sud et l'Est", "Le Centre", "L'Adamaoua"]

# culture agricole -> (zone principale, precision, difficulte)
CULTURES = {
    "le coton": ("Le Grand Nord", "il est encadre par la SODECOTON", MOYEN),
    "le cacao": ("Le Centre", "le Cameroun figure parmi les premiers producteurs mondiaux", FACILE),
    "le cafe arabica": ("L'Ouest et le Nord-Ouest", "il pousse sur les hautes terres", MOYEN),
    "le cafe robusta": ("Le Littoral et le Sud-Ouest", "il pousse en zone chaude et humide", MOYEN),
    "la banane d'exportation": ("Le Littoral et le Sud-Ouest", "elle est cultivee autour du Moungo et du Fako", MOYEN),
    "l'hevea": ("Le Littoral et le Sud-Ouest", "il fournit le caoutchouc naturel", MOYEN),
    "le palmier a huile": ("Le Littoral et le Sud-Ouest", "il alimente l'industrie de l'huile de palme", MOYEN),
    "le mil et le sorgho": ("Le Grand Nord", "ce sont les cereales de base en zone sahelienne", MOYEN),
    "l'oignon": ("Le Grand Nord", "la region de Maroua en est un bassin reconnu", CHALLENGE),
    "la pomme de terre": ("L'Ouest et le Nord-Ouest", "les hautes terres offrent un climat favorable", MOYEN),
    "le poivre de Penja": ("Le Littoral et le Sud-Ouest", "il beneficie d'une indication geographique protegee", MOYEN),
    "l'ananas": ("Le Littoral et le Sud-Ouest", "il est cultive dans le Moungo", CHALLENGE),
    "le manioc": ("Le Sud et l'Est", "il sert a preparer bobolo, gari et miondo", FACILE),
    "le plantain": ("Le Sud et l'Est", "il accompagne de nombreux plats camerounais", FACILE),
    "l'igname": ("Le Grand Nord", "elle est notamment cultivee autour de Tibati et du Mbam", CHALLENGE),
    "le riz": ("Le Grand Nord", "la SEMRY exploite les perimetres de Yagoua et Maga", CHALLENGE),
    "le the": ("L'Ouest et le Nord-Ouest", "les plantations de Djuttitsa et Ndu sont connues", CHALLENGE),
    "le mais": ("L'Ouest et le Nord-Ouest", "il est une cereale de base des hautes terres", MOYEN),
    "l'arachide": ("Le Grand Nord", "elle entre dans la preparation du ndole et des sauces", MOYEN),
    "le miel blanc d'Oku": ("L'Ouest et le Nord-Ouest", "il beneficie d'une indication geographique protegee", CHALLENGE),
}

ECONOMIE = [
    ("Quel produit agricole d'exportation place le Cameroun parmi les premiers producteurs mondiaux ?",
     "Le cacao", ["Le ble", "Le riz", "La vigne"], FACILE, "Le Cameroun est un acteur majeur du cacao mondial."),
    ("Quels deux produits camerounais beneficient d'une indication geographique protegee reconnue ?",
     "Le poivre de Penja et le miel blanc d'Oku",
     ["Le cacao de Kribi et le the de Buea", "Le riz de Yagoua et le mais de Ndop",
      "Le safou de Bafia et l'ananas de Loum"], CHALLENGE,
     "Ces deux produits ont obtenu une IGP reconnue a l'international."),
    ("Quelle est la principale ressource miniere exportee par le Cameroun ?", "Le petrole brut",
     ["L'or uniquement", "Le diamant uniquement", "Le charbon"], MOYEN,
     "Le petrole reste la premiere ressource d'exportation en valeur."),
    ("Quel gisement de fer, dans la region du Sud, fait l'objet de projets miniers ?", "Le gisement de Mbalam",
     ["Le gisement de Waza", "Le gisement de Ndop", "Le gisement de Bafang"], CHALLENGE,
     "Mbalam-Nabeba est un projet de minerai de fer transfrontalier."),
    ("Quel gisement de bauxite est situe dans l'Adamaoua ?", "Le gisement de Minim-Martap",
     ["Le gisement de Kribi", "Le gisement de Mamfe", "Le gisement de Bertoua"], CHALLENGE,
     "Minim-Martap est l'un des principaux gisements de bauxite du pays."),
    ("Quelle industrie d'Edea transforme l'alumine importee en aluminium ?", "ALUCAM",
     ["CICAM", "SOSUCAM", "CAMRAIL"], MOYEN, "ALUCAM profite de l'energie du barrage de Song Loulou."),
    ("Quel est le principal debouche du bois camerounais ?", "L'exportation, notamment vers l'Europe et l'Asie",
     ["La consommation locale uniquement", "La production de papier journal uniquement",
      "La fabrication de vehicules"], MOYEN, "La filiere bois est un poste d'exportation important."),
    ("Quelle politique de developpement le Cameroun a-t-il adoptee pour la periode 2020-2030 ?",
     "La Strategie Nationale de Developpement 2030 (SND30)",
     ["Le Plan Marshall", "L'Agenda 2063 national", "Le Programme SAP"], CHALLENGE,
     "La SND30 a succede au DSCE."),
    ("Quel secteur emploie la plus grande part de la population active camerounaise ?", "L'agriculture",
     ["L'industrie lourde", "La finance", "L'aeronautique"], FACILE,
     "L'agriculture reste le premier employeur du pays."),
    ("Que designe le secteur informel au Cameroun ?",
     "L'ensemble des activites economiques non enregistrees officiellement",
     ["Les entreprises publiques", "Les societes cotees en bourse", "Les ONG internationales"], FACILE,
     "Le secteur informel represente une large part de l'emploi au Cameroun."),
    ("Quelle est la part approximative de l'emploi informel dans l'economie camerounaise ?",
     "Plus de 80 %", ["Environ 10 %", "Environ 30 %", "Environ 50 %"], MOYEN,
     "L'essentiel des emplois se situe dans l'informel."),
    ("Quel service permet d'envoyer de l'argent depuis un telephone au Cameroun ?", "Le mobile money",
     ["Le telegramme", "Le mandat postal uniquement", "Le cheque de banque"], FACILE,
     "MTN MoMo et Orange Money sont largement utilises."),
    ("Quelle bourse des valeurs mobilieres est basee a Douala et integree au marche regional ?",
     "La Bourse des Valeurs Mobilieres de l'Afrique Centrale (BVMAC)",
     ["La BRVM", "La Bourse de Lagos", "La Bourse de Nairobi"], CHALLENGE,
     "La BVMAC, unifiee en 2019, a son siege a Douala."),
    ("Quel taux de TVA s'applique generalement au Cameroun, centimes additionnels compris ?",
     "19,25 %", ["18 %", "20 %", "15 %"], MOYEN, "La TVA est de 17,5 % plus 10 % de centimes additionnels."),
    ("Quel impot libere les petites entreprises camerounaises de faible chiffre d'affaires ?",
     "L'impot libératoire", ["L'impot sur les societes", "La taxe fonciere", "La taxe d'apprentissage"], MOYEN,
     "L'impot libératoire vise les tres petites activites."),
    ("Quel document atteste l'immatriculation d'une entreprise au fichier des contribuables camerounais ?",
     "La carte de contribuable (numero d'identifiant unique)",
     ["Le passeport", "Le permis de conduire", "La carte d'electeur"], MOYEN,
     "Le NIU identifie l'entreprise aupres du fisc."),
    ("Ou une entreprise camerounaise accomplit-elle ses formalites de creation en un seul lieu ?",
     "Au Centre de Formalites de Creation des Entreprises (CFCE)",
     ["A la mairie uniquement", "A la prefecture uniquement", "A l'Assemblee nationale"], MOYEN,
     "Le CFCE regroupe les administrations concernees."),
    ("Quel registre camerounais enregistre officiellement les societes commerciales ?",
     "Le Registre du Commerce et du Credit Mobilier (RCCM)",
     ["Le cadastre", "Le registre d'etat civil", "Le registre foncier"], MOYEN,
     "Le RCCM est prevu par le droit OHADA."),
    ("Quel corridor routier relie Douala a N'Djamena et Bangui ?",
     "Le corridor Douala-Tchad-RCA", ["Le corridor Abidjan-Lagos", "Le corridor Nord-Sud",
      "Le corridor du Nil"], MOYEN, "Le port de Douala sert de porte d'entree pour le Tchad et la RCA."),
    ("Quel projet de zone industrielle a ete developpe autour du port de Kribi ?",
     "La zone industrialo-portuaire de Kribi", ["La zone franche de Waza", "Le technopole de Maroua",
      "La zone industrielle de Bertoua"], CHALLENGE, "Kribi combine port en eau profonde et zone industrielle."),
    ("Quelle autoroute a ete construite pour relier Douala a Yaounde par phases ?",
     "L'autoroute Yaounde-Douala", ["L'autoroute Garoua-Maroua", "L'autoroute Kribi-Ebolowa",
      "L'autoroute Bamenda-Bafoussam"], MOYEN, "Le premier troncon relie Yaounde a Boumnyebel."),
    ("Quelle ligne ferroviaire relie Douala au Nord du Cameroun ?", "La ligne Douala-Ngaoundere (Transcamerounais)",
     ["La ligne Kribi-Maroua", "La ligne Bamenda-Bertoua", "La ligne Buea-Yaounde"], MOYEN,
     "Le Transcamerounais dessert Yaounde, Belabo et Ngaoundere."),
    ("Quel aeroport international dessert la capitale politique du Cameroun ?", "L'aeroport de Yaounde-Nsimalen",
     ["L'aeroport de Douala", "L'aeroport de Garoua", "L'aeroport de Maroua-Salak"], MOYEN,
     "Nsimalen est l'aeroport international de Yaounde."),
    ("Quel aeroport camerounais traite le plus grand trafic de passagers ?", "L'aeroport international de Douala",
     ["L'aeroport de Bamenda", "L'aeroport de Bertoua", "L'aeroport de Ngaoundere"], MOYEN,
     "Douala est la principale porte d'entree aerienne."),
    ("Quel est le nom du programme camerounais d'appui a l'auto-emploi dans le secteur informel ?",
     "Le PIAASI", ["Le PADER", "Le PNDP", "Le PACA"], CHALLENGE,
     "Le Programme Integre d'Appui aux Acteurs du Secteur Informel."),
    ("Quelle banque publique camerounaise a ete creee pour financer les PME ?",
     "La Banque Camerounaise des PME (BC-PME)", ["La BEAC", "La BICEC", "La SNI"], MOYEN,
     "La BC-PME finance specifiquement les petites et moyennes entreprises."),
    ("Comment appelle-t-on les etablissements financiers de proximite tres presents au Cameroun ?",
     "Les etablissements de microfinance (EMF)", ["Les fonds souverains", "Les banques centrales",
      "Les compagnies d'assurance-vie"], FACILE, "Les EMF financent les petites activites."),
    ("Quel reseau cooperatif d'epargne et de credit est tres implante dans les regions anglophones ?",
     "Les Credit Unions (CamCCUL)", ["Les caisses de retraite", "Les fonds de pension europeens",
      "Les banques d'affaires"], CHALLENGE, "CamCCUL federe les cooperatives d'epargne et de credit."),
    ("Quelle organisation regionale harmonise le droit des affaires dans 17 pays africains ?",
     "L'OHADA", ["L'OMC", "La CNUCED", "Le FMI"], MOYEN,
     "L'OHADA harmonise le droit commercial, comptable et des societes."),
    ("Quel systeme comptable les entreprises camerounaises appliquent-elles ?", "Le SYSCOHADA revise",
     ["Le plan comptable francais 1982", "Les IFRS obligatoires pour toutes",
      "Le plan comptable americain"], CHALLENGE, "Le SYSCOHADA revise est en vigueur depuis 2018."),
    ("Quelle forme juridique est la plus utilisee par les PME camerounaises ?",
     "La SARL (Societe a Responsabilite Limitee)", ["La SA cotee", "Le GIE international",
      "La societe anonyme europeenne"], MOYEN, "La SARL est simple a creer et limite la responsabilite."),
    ("Quel capital social minimum le droit OHADA exige-t-il pour une SARL ?",
     "Il est librement fixe par les statuts dans plusieurs Etats, souvent 100 000 FCFA",
     ["10 000 000 FCFA obligatoires", "50 000 000 FCFA obligatoires", "Aucun statut n'est requis"], CHALLENGE,
     "La reforme a assoupli le capital minimum de la SARL."),
    ("Quel est le taux normal de l'impot sur les societes au Cameroun ?", "Environ 33 % avec les centimes additionnels",
     ["10 %", "50 %", "75 %"], CHALLENGE, "Le taux de base est de 30 % plus 10 % de centimes additionnels."),
    ("Quel salaire minimum interprofessionnel garanti s'applique au Cameroun (SMIG) ?",
     "Environ 41 875 FCFA par mois", ["Environ 5 000 FCFA", "Environ 250 000 FCFA",
      "Environ 1 000 000 FCFA"], CHALLENGE, "Le SMIG a ete revalorise a 41 875 FCFA en 2023."),
    ("Quel document social une entreprise camerounaise doit-elle etablir pour ses salaries chaque mois ?",
     "Le bulletin de paie", ["Le bilan comptable", "Le compte de resultat", "Le rapport d'audit"], FACILE,
     "Le bulletin de paie accompagne le versement du salaire."),
    ("Quelle plateforme camerounaise permet de payer certains impots en ligne ?",
     "Le portail des impots en ligne de la DGI", ["Le site du Senat", "La plateforme ELECAM",
      "Le portail de la CRTV"], MOYEN, "La Direction Generale des Impots a digitalise plusieurs procedures."),
    ("Que designe le sigle PME dans le contexte camerounais ?",
     "Petites et Moyennes Entreprises", ["Programme Militaire d'Etat", "Plan Municipal Economique",
      "Projet Mondial d'Exportation"], FACILE, "Les PME representent la grande majorite du tissu economique."),
    ("Quelle part approximative du tissu economique camerounais les PME representent-elles ?",
     "Plus de 90 % des entreprises", ["Environ 20 %", "Environ 45 %", "Moins de 5 %"], MOYEN,
     "Les PME et TPE constituent l'essentiel des entreprises enregistrees."),
    ("Quel salon camerounais met en avant les produits fabriques au Cameroun ?",
     "Le salon Promote", ["Le SIAO", "Le FESPACO", "Le SITEV"], MOYEN,
     "Promote est un grand salon international de l'entreprise a Yaounde."),
    ("Quel concept encourage les Camerounais a privilegier les produits locaux ?",
     "Le Made in Cameroon", ["Le libre-echange total", "L'importation prioritaire",
      "La delocalisation industrielle"], FACILE, "Le Made in Cameroon soutient la production nationale."),
    ("Quelle institution camerounaise controle la qualite et la normalisation des produits ?",
     "L'ANOR (Agence des Normes et de la Qualite)", ["La CONAC", "L'ARMP", "ELECAM"], CHALLENGE,
     "L'ANOR definit et controle les normes camerounaises."),
    ("Quelle taxe est prelevee sur les marchandises importees au Cameroun ?", "Le droit de douane",
     ["La taxe de sejour", "La redevance audiovisuelle", "La taxe fonciere"], FACILE,
     "Les droits de douane s'appliquent aux importations."),
    ("Quel port camerounais est specialise dans l'exportation de la banane du Sud-Ouest ?",
     "Le port de Tiko", ["Le port de Garoua", "Le port de Yagoua", "Le port de Bertoua"], CHALLENGE,
     "Tiko et Limbe servent aux exportations agricoles du Sud-Ouest."),
    ("Quel projet gazier a permis au Cameroun d'exporter du gaz naturel liquefie ?",
     "Le projet de GNL flottant de Kribi", ["Le projet solaire de Maroua", "Le barrage de Memve'ele",
      "Le pipeline Tchad-Cameroun uniquement"], CHALLENGE,
     "Une unite flottante de liquefaction opere au large de Kribi."),
    ("Quel oleoduc traverse le Cameroun pour exporter le petrole d'un pays voisin ?",
     "Le pipeline Tchad-Cameroun", ["Le pipeline Nigeria-Cameroun", "Le pipeline Gabon-Cameroun",
      "Le pipeline Congo-Cameroun"], MOYEN, "Le petrole tchadien est exporte via le terminal de Kribi."),
]


def build() -> list[Q]:
    qs: list[Q] = []
    precisions = [v[1] for v in CULTURES.values()]
    for culture, (zone, precision, diff) in CULTURES.items():
        qs.append(Q(
            f"Dans quelle partie du Cameroun {culture} est-il ou est-elle principalement cultive(e) ?",
            zone, others(culture, ZONES), diff, "cameroun,economie,agriculture",
            f"Pour {culture} : {precision}.",
        ))
        qs.append(Q(
            f"Quelle affirmation est exacte a propos de {culture} au Cameroun ?",
            f"En resume, {precision}", others(culture + "p", [f"En resume, {p}" for p in precisions]),
            diff, "cameroun,economie,agriculture", f"Pour {culture} : {precision}.",
        ))
    for question, correct, wrong, diff, expl in ECONOMIE:
        qs.append(Q(question, correct, wrong, diff, "cameroun,economie", expl))
    return qs
