# -*- coding: utf-8 -*-
"""Banque Cameroun : histoire, symboles nationaux et institutions."""

from __future__ import annotations

from .common import CHALLENGE, FACILE, MOYEN, Q

HISTOIRE = [
    ("Quel navigateur portugais a donne son nom au Cameroun en 1472 en decouvrant des crevettes dans un fleuve ?",
     "Fernando Poo", ["Vasco de Gama", "Christophe Colomb", "Bartolomeu Dias"], MOYEN,
     "Rio dos Camaroes, la riviere des crevettes, a donne le nom Cameroun."),
    ("Que signifie l'expression portugaise Rio dos Camaroes a l'origine du nom Cameroun ?",
     "La riviere des crevettes", ["Le fleuve des lions", "La baie des palmiers", "Le port des epices"], FACILE,
     "Les Portugais avaient trouve le Wouri rempli de crevettes."),
    ("Quel fleuve a ete baptise Rio dos Camaroes par les Portugais ?",
     "Le Wouri", ["La Sanaga", "Le Nyong", "Le Ntem"], MOYEN,
     "L'estuaire du Wouri est a l'origine du nom du pays."),
    ("En quelle annee le traite germano-douala a-t-il place le Cameroun sous protectorat allemand ?",
     "1884", ["1872", "1901", "1916"], MOYEN, "Le traite a ete signe le 12 juillet 1884."),
    ("Quel explorateur allemand a signe le traite de protectorat de 1884 avec les rois douala ?",
     "Gustav Nachtigal", ["Otto von Bismarck", "Carl Peters", "Heinrich Barth"], CHALLENGE,
     "Gustav Nachtigal representait l'Empire allemand."),
    ("Comment s'appelait le Cameroun a l'epoque de la colonisation allemande ?",
     "Kamerun", ["Kamerland", "Deutsch-Guinea", "Neu-Afrika"], MOYEN, "Le territoire etait nomme Kamerun."),
    ("Quelle ville a servi de capitale du Kamerun allemand a partir de 1901 ?",
     "Buea", ["Douala", "Yaounde", "Kribi"], CHALLENGE,
     "La capitale a ete transferee de Douala a Buea en 1901."),
    ("Quel roi douala a ete pendu par les Allemands en 1914 pour avoir defendu les terres de son peuple ?",
     "Rudolf Douala Manga Bell", ["Charles Atangana", "Njoya", "Martin-Paul Samba"], MOYEN,
     "Rudolf Douala Manga Bell est un heros national."),
    ("Apres la Premiere Guerre mondiale, entre quelles deux puissances le Cameroun a-t-il ete partage ?",
     "La France et le Royaume-Uni", ["La Belgique et le Portugal", "L'Espagne et l'Italie", "Les Pays-Bas et la France"], MOYEN,
     "Le partage a suivi la defaite allemande de 1916."),
    ("En quelle annee la Societe des Nations a-t-elle place le Cameroun sous mandat franco-britannique ?",
     "1922", ["1916", "1930", "1946"], CHALLENGE, "Les mandats de la SDN datent de 1922."),
    ("Quel parti politique a mene la lutte pour l'independance du Cameroun a partir de 1948 ?",
     "L'UPC (Union des Populations du Cameroun)", ["Le RDPC", "Le SDF", "L'UNDP"], MOYEN,
     "L'UPC a ete fondee le 10 avril 1948."),
    ("Qui etait le secretaire general historique de l'UPC, tue en 1958 ?",
     "Ruben Um Nyobe", ["Felix-Roland Moumie", "Ernest Ouandie", "Ahmadou Ahidjo"], MOYEN,
     "Ruben Um Nyobe est tombe le 13 septembre 1958."),
    ("En quelle annee le Cameroun sous administration francaise a-t-il accede a l'independance ?",
     "1960", ["1958", "1961", "1972"], FACILE, "L'independance a ete proclamee le 1er janvier 1960."),
    ("Quelle date correspond a l'independance du Cameroun sous tutelle francaise ?",
     "Le 1er janvier 1960", ["Le 20 mai 1972", "Le 1er octobre 1961", "Le 11 fevrier 1961"], MOYEN,
     "Le 1er janvier 1960 marque l'independance."),
    ("Qui a ete le premier president de la Republique du Cameroun ?",
     "Ahmadou Ahidjo", ["Paul Biya", "John Ngu Foncha", "Ruben Um Nyobe"], FACILE,
     "Ahmadou Ahidjo a dirige le pays de 1960 a 1982."),
    ("Que s'est-il passe le 1er octobre 1961 au Cameroun ?",
     "La reunification avec le Southern Cameroons britannique",
     ["La proclamation de l'independance", "L'adoption de l'Etat unitaire", "La creation du Sénat"], MOYEN,
     "Le Cameroun meridional britannique a rejoint la Republique."),
    ("Quel etait le nom de l'Etat cree apres la reunification de 1961 ?",
     "La Republique federale du Cameroun", ["La Republique unie du Cameroun", "L'Union camerounaise", "Le Royaume du Cameroun"], CHALLENGE,
     "La federation a dure jusqu'au referendum de 1972."),
    ("Que celebre le Cameroun le 20 mai, jour de sa fete nationale ?",
     "Le referendum de 1972 instituant l'Etat unitaire",
     ["L'independance de 1960", "La reunification de 1961", "La fin de la colonisation allemande"], MOYEN,
     "Le 20 mai 1972, le Cameroun est devenu un Etat unitaire."),
    ("Quelle fete nationale le Cameroun celebre-t-il le 11 fevrier ?",
     "La Fete de la Jeunesse", ["La Fete du Travail", "La Fete de l'Unite", "La Fete de l'Independance"], FACILE,
     "Le 11 fevrier est la Fete nationale de la Jeunesse."),
    ("En quelle annee Paul Biya est-il devenu president de la Republique ?",
     "1982", ["1975", "1990", "1992"], FACILE, "Paul Biya a prete serment le 6 novembre 1982."),
    ("Quelle fonction Paul Biya occupait-il avant de devenir president en 1982 ?",
     "Premier ministre", ["Ministre des Finances", "President de l'Assemblee nationale", "Gouverneur du Littoral"], MOYEN,
     "Il etait Premier ministre depuis 1975."),
    ("En quelle annee le multipartisme a-t-il ete retabli au Cameroun ?",
     "1990", ["1982", "1985", "1996"], MOYEN, "La loi sur les libertes date du 19 decembre 1990."),
    ("Quel parti politique a ete lance a Bamenda le 26 mai 1990 ?",
     "Le Social Democratic Front (SDF)", ["Le RDPC", "L'UPC", "L'UNDP"], MOYEN,
     "Le SDF a ete fonde par Ni John Fru Ndi."),
    ("Quel est le nom du parti au pouvoir au Cameroun depuis 1985 ?",
     "Le RDPC (Rassemblement Democratique du Peuple Camerounais)",
     ["Le SDF", "L'UPC", "L'UNDP"], MOYEN, "Le RDPC a succede a l'UNC lors du congres de Bamenda en 1985."),
    ("En quelle annee le Cameroun a-t-il rejoint le Commonwealth ?",
     "1995", ["1985", "1990", "2000"], CHALLENGE, "Le Cameroun est membre du Commonwealth depuis 1995."),
    ("Le Cameroun est membre a la fois du Commonwealth et de quelle autre grande organisation linguistique ?",
     "La Francophonie", ["La Ligue arabe", "Le Mercosur", "L'ASEAN"], FACILE,
     "Le bilinguisme francais-anglais explique cette double appartenance."),
    ("Quelle juridiction internationale a tranche le differend de Bakassi en 2002 ?",
     "La Cour internationale de justice", ["Le Conseil de securite de l'ONU", "L'Union africaine", "La Cour penale internationale"], MOYEN,
     "La CIJ de La Haye a rendu son arret le 10 octobre 2002."),
    ("Quel accord a organise la retrocession de Bakassi au Cameroun ?",
     "L'accord de Greentree", ["L'accord de Yaounde", "L'accord d'Abuja", "L'accord de Douala"], CHALLENGE,
     "L'accord de Greentree a ete signe en 2006."),
    ("Quelle constitution regit aujourd'hui le Cameroun, apres sa revision majeure ?",
     "La constitution de 1972 revisee en 1996", ["La constitution de 1960", "La constitution de 1984", "La constitution de 2008"], CHALLENGE,
     "La loi du 18 janvier 1996 a profondement revise la constitution de 1972."),
    ("Quel changement de nom l'Etat camerounais a-t-il adopte en 1984 ?",
     "Il est passe de Republique unie du Cameroun a Republique du Cameroun",
     ["Il est passe de Kamerun a Cameroun", "Il est devenu Republique federale", "Il est devenu Royaume du Cameroun"], CHALLENGE,
     "Le changement de denomination date du 4 fevrier 1984."),
]

SYMBOLES = [
    ("Quelles sont les couleurs du drapeau camerounais ?", "Vert, rouge et jaune",
     ["Vert, blanc et rouge", "Bleu, jaune et rouge", "Noir, rouge et vert"], FACILE,
     "Le drapeau est un tricolore vertical vert, rouge et jaune."),
    ("Que porte la bande centrale du drapeau camerounais ?", "Une etoile d'or",
     ["Un lion", "Un baobab", "Un croissant de lune"], FACILE,
     "L'etoile d'or symbolise l'unite nationale."),
    ("Quelle est la devise de la Republique du Cameroun ?", "Paix - Travail - Patrie",
     ["Unite - Progres - Justice", "Liberte - Egalite - Fraternite", "Force - Union - Avenir"], FACILE,
     "La devise nationale est Paix - Travail - Patrie."),
    ("Comment appelle-t-on l'hymne national camerounais ?", "Le Chant de Ralliement",
     ["La Marche des Lions", "L'Hymne de l'Unite", "Le Chant du Wouri"], MOYEN,
     "O Cameroun berceau de nos ancetres est appele le Chant de Ralliement."),
    ("Quelles sont les deux langues officielles du Cameroun ?", "Le francais et l'anglais",
     ["Le francais et l'allemand", "L'anglais et le douala", "Le francais et le fulfulde"], FACILE,
     "Le bilinguisme officiel decoule de l'histoire coloniale."),
    ("Quelle monnaie utilise-t-on au Cameroun ?", "Le franc CFA",
     ["Le naira", "Le cedi", "Le dirham"], FACILE, "Le Cameroun utilise le franc CFA d'Afrique centrale."),
    ("Quelle banque centrale emet la monnaie utilisee au Cameroun ?", "La BEAC",
     ["La BCEAO", "La Banque mondiale", "La BAD"], MOYEN,
     "La Banque des Etats de l'Afrique centrale a son siege a Yaounde."),
    ("Dans quelle ville se trouve le siege de la BEAC ?", "Yaounde",
     ["Libreville", "Bangui", "Douala"], CHALLENGE, "Le siege de la BEAC est a Yaounde."),
    ("A quelle communaute economique regionale le Cameroun appartient-il ?", "La CEMAC",
     ["La CEDEAO", "La SADC", "L'UEMOA"], MOYEN,
     "La Communaute economique et monetaire de l'Afrique centrale."),
    ("Combien d'Etats membres compte la CEMAC ?", "Six",
     ["Quatre", "Huit", "Quinze"], CHALLENGE,
     "Cameroun, Congo, Gabon, Guinee equatoriale, RCA et Tchad."),
    ("Quel animal figure sur les armoiries et symbolise le Cameroun ?", "Le lion",
     ["L'elephant", "La panthere", "L'aigle"], FACILE, "Le lion inspire le surnom des Lions Indomptables."),
    ("Quelle est la fete du Travail celebree au Cameroun ?", "Le 1er mai",
     ["Le 20 mai", "Le 11 fevrier", "Le 1er octobre"], FACILE, "Le 1er mai est ferie au Cameroun."),
    ("Combien de deputes compte l'Assemblee nationale du Cameroun ?", "180",
     ["100", "150", "250"], CHALLENGE, "L'Assemblee nationale compte 180 deputes."),
    ("Combien de senateurs compte le Senat camerounais ?", "100",
     ["60", "180", "120"], CHALLENGE, "70 senateurs sont elus et 30 nommes par le president."),
    ("En quelle annee le Senat camerounais a-t-il ete mis en place ?", "2013",
     ["1996", "2005", "2018"], CHALLENGE, "Les premieres elections senatoriales ont eu lieu en avril 2013."),
    ("Quel organe organise les elections au Cameroun ?", "ELECAM",
     ["La CONAC", "Le CNC", "L'ARMP"], MOYEN, "Elections Cameroon est l'organe de gestion des scrutins."),
    ("Que designe la CONAC au Cameroun ?", "La Commission nationale anti-corruption",
     ["La Commission nationale des concours", "Le Conseil national du commerce", "La Caisse nationale de credit"], MOYEN,
     "La CONAC lutte contre la corruption."),
    ("Quel organisme gere la securite sociale des travailleurs au Cameroun ?", "La CNPS",
     ["La CNSS", "L'INPS", "La CNAM"], MOYEN, "La Caisse Nationale de Prevoyance Sociale."),
    ("Quelle institution camerounaise accompagne l'emploi et l'insertion professionnelle ?", "Le Fonds National de l'Emploi (FNE)",
     ["La CNPS", "L'ARMP", "La CONAC"], MOYEN, "Le FNE finance des formations et des projets d'insertion."),
    ("Quelle agence publique camerounaise est dediee a la promotion des PME ?", "L'APME",
     ["L'ARMP", "La SNI", "La CONAC"], MOYEN, "L'Agence de promotion des PME accompagne les entrepreneurs."),
    ("Quel est le role du Guichet unique du commerce exterieur (GUCE) au Cameroun ?",
     "Simplifier les formalites d'import-export en un seul point",
     ["Collecter les impots sur les salaires", "Delivrer les passeports", "Gerer les bourses scolaires"], MOYEN,
     "Le GUCE regroupe les administrations liees au commerce exterieur."),
    ("Quelle organisation patronale regroupe les grandes entreprises camerounaises ?", "Le GICAM",
     ["Le SYNDUSTRICAM uniquement", "La CONAC", "L'ARMP"], MOYEN,
     "Le Groupement inter-patronal du Cameroun."),
    ("Quelle chambre consulaire accompagne les commercants et industriels camerounais ?",
     "La Chambre de Commerce, d'Industrie, des Mines et de l'Artisanat (CCIMA)",
     ["Le Senat", "La CONAC", "Le CNC"], MOYEN, "La CCIMA represente le secteur prive aupres de l'Etat."),
    ("Quelle est la duree du mandat presidentiel au Cameroun depuis la revision de 2008 ?", "Sept ans renouvelable",
     ["Cinq ans non renouvelable", "Quatre ans", "Six ans"], CHALLENGE,
     "Le mandat de sept ans est renouvelable depuis 2008."),
    ("Comment appelle-t-on les collectivites de base dirigees par un maire au Cameroun ?", "Les communes",
     ["Les prefectures", "Les cantons", "Les provinces"], FACILE, "Le Cameroun compte environ 360 communes."),
    ("Qui represente l'Etat a la tete d'un departement au Cameroun ?", "Le prefet",
     ["Le maire", "Le gouverneur", "Le sous-prefet"], MOYEN, "Le prefet dirige le departement, le gouverneur la region."),
    ("Qui represente l'Etat a la tete d'une region au Cameroun ?", "Le gouverneur",
     ["Le prefet", "Le maire", "Le sous-prefet"], MOYEN, "Le gouverneur est nomme par decret presidentiel."),
    ("Quelle reforme majeure a renforce les competences des regions camerounaises en 2019 ?",
     "La loi sur la decentralisation et le Code general des collectivites territoriales",
     ["La creation du Senat", "La revision du code penal", "La loi sur le multipartisme"], CHALLENGE,
     "Le Code general des CTD a ete promulgue en decembre 2019."),
    ("Quelle organisation regionale a son secretariat permanent a Yaounde et harmonise le droit des affaires ?",
     "L'OHADA", ["La CEDEAO", "L'UEMOA", "La SADC"], MOYEN,
     "Le Secretariat permanent de l'OHADA est bien base a Yaounde."),
]


def build() -> list[Q]:
    qs: list[Q] = []
    for question, correct, wrong, diff, expl in HISTOIRE:
        qs.append(Q(question, correct, wrong, diff, "cameroun,histoire", expl))
    for question, correct, wrong, diff, expl in SYMBOLES:
        qs.append(Q(question, correct, wrong, diff, "cameroun,institutions,symboles", expl))
    return qs
