# -*- coding: utf-8 -*-
"""Banque Cameroun : questions accessibles (niveau facile) pour lancer la partie."""

from __future__ import annotations

from .common import cap, CHALLENGE, FACILE, MOYEN, Q, others
from .cameroun_geo import DEPARTEMENTS

NB_DEPTS = {}
for _dept, (_chef, _region) in DEPARTEMENTS.items():
    NB_DEPTS[_region] = NB_DEPTS.get(_region, 0) + 1

FRONTIERES = {
    "le Nigeria": "a l'ouest et au nord-ouest",
    "le Tchad": "au nord-est",
    "la Republique centrafricaine": "a l'est",
    "le Congo": "au sud-est",
    "le Gabon": "au sud",
    "la Guinee equatoriale": "au sud-ouest",
}

FACILES = [
    ("Sur quel continent se trouve le Cameroun ?", "L'Afrique",
     ["L'Asie", "L'Europe", "L'Amerique du Sud"], "Le Cameroun est en Afrique centrale."),
    ("Dans quelle partie de l'Afrique se situe le Cameroun ?", "En Afrique centrale",
     ["En Afrique du Nord", "En Afrique australe", "Dans la Corne de l'Afrique"], "Le Cameroun appartient a l'Afrique centrale."),
    ("Quel pays a pour capitale Yaounde ?", "Le Cameroun",
     ["Le Gabon", "Le Tchad", "Le Congo"], "Yaounde est la capitale du Cameroun."),
    ("Quel est le surnom touristique du Cameroun ?", "L'Afrique en miniature",
     ["Le pays des mille collines", "La perle de l'Atlantique", "Le grenier du Sahel"], "Le Cameroun reunit tous les paysages du continent."),
    ("Quelle equipe de football represente le Cameroun ?", "Les Lions Indomptables",
     ["Les Elephants", "Les Aigles de Carthage", "Les Black Stars"], "Les Lions Indomptables sont l'equipe nationale."),
    ("Quel sport est le plus populaire au Cameroun ?", "Le football",
     ["Le hockey sur glace", "Le cricket", "Le ski alpin"], "Le football est le sport roi du pays."),
    ("Quelle boisson chaude est produite dans les hautes terres de l'Ouest camerounais ?", "Le cafe",
     ["Le mate", "Le sirop d'erable", "Le the vert japonais"], "L'arabica est cultive sur les hautes terres."),
    ("Quel fruit tropical est tres consomme au Cameroun ?", "La mangue",
     ["La pomme des Alpes", "La cerise du Japon", "Le raisin de Bourgogne"], "Mangues, ananas et papayes sont courants."),
    ("Quel plat de riz ou de macabo accompagne souvent les sauces camerounaises ?", "Le riz blanc",
     ["Les sushis", "Les pates a la carbonara", "Le couscous marocain"], "Le riz accompagne de nombreuses sauces."),
    ("Comment appelle-t-on la monnaie utilisee dans les marches camerounais ?", "Le franc CFA",
     ["L'euro", "Le dollar", "La livre sterling"], "Le franc CFA est la monnaie du Cameroun."),
    ("Quelle langue officielle est la plus parlee dans la region du Centre ?", "Le francais",
     ["L'espagnol", "Le portugais", "L'arabe"], "Le Centre est une region francophone."),
    ("Quelle langue officielle est majoritaire dans la region du Sud-Ouest ?", "L'anglais",
     ["L'allemand", "L'italien", "Le russe"], "Le Sud-Ouest est une region anglophone."),
    ("Comment appelle-t-on une personne originaire du Cameroun ?", "Un Camerounais",
     ["Un Congolais", "Un Gabonais", "Un Tchadien"], "Les habitants du Cameroun sont les Camerounais."),
    ("Quelle ville camerounaise possede le principal port du pays ?", "Douala",
     ["Bafoussam", "Ngaoundere", "Bertoua"], "Le port de Douala est le poumon economique."),
    ("Quel moyen de transport relie Douala a Ngaoundere ?", "Le train",
     ["Le metro", "Le tramway", "Le teleferique"], "Le Transcamerounais relie Douala au Nord."),
    ("Quel type de climat trouve-t-on sur la cote camerounaise ?", "Un climat chaud et humide",
     ["Un climat polaire", "Un climat desertique glacial", "Un climat de toundra"], "La cote est chaude et tres arrosee."),
    ("Quelle mer ou quel ocean borde Kribi ?", "L'ocean Atlantique",
     ["La Mediterranee", "L'ocean Indien", "La mer Noire"], "Kribi est une station balneaire de l'Atlantique."),
    ("Quel est le plus haut sommet visible depuis Buea ?", "Le mont Cameroun",
     ["Le Kilimandjaro", "Le mont Blanc", "L'Everest"], "Buea est situee au pied du mont Cameroun."),
    ("Que trouve-t-on principalement dans la region de l'Est du Cameroun ?", "De vastes forets",
     ["Des glaciers", "Des deserts de sel", "Des fjords"], "L'Est est couvert de foret dense."),
    ("Quelle activite pratique-t-on beaucoup dans les villages camerounais ?", "L'agriculture",
     ["L'exploitation petroliere offshore", "La construction navale", "La production de neige artificielle"], "L'agriculture fait vivre la majorite des zones rurales."),
    ("Quel jour de la semaine se tiennent traditionnellement les grands marches ruraux au Cameroun ?",
     "Cela varie selon les villages, souvent un jour fixe par semaine",
     ["Uniquement le dimanche partout", "Uniquement le 1er janvier", "Jamais, il n'y a pas de marches"],
     "Chaque localite a son jour de marche."),
    ("Comment appelle-t-on un commercant qui vend a la sauvette au bord de la route ?", "Un sauveteur",
     ["Un banquier", "Un notaire", "Un pilote"], "Le sauveteur est une figure du commerce de rue."),
    ("Quel service permet de payer sa facture d'electricite depuis son telephone ?", "Le mobile money",
     ["Le fax", "Le telegramme", "La lettre recommandee"], "Le mobile money simplifie les paiements."),
    ("Quelle entreprise fournit l'electricite a la plupart des menages camerounais ?", "ENEO",
     ["CAMWATER", "CAMPOST", "CAMRAIL"], "ENEO distribue l'electricite."),
    ("Quelle entreprise fournit l'eau potable dans les villes camerounaises ?", "CAMWATER",
     ["ENEO", "CAMTEL", "CAMPOST"], "CAMWATER assure la production et la distribution d'eau."),
    ("Quel evenement national est celebre chaque 20 mai au Cameroun ?", "La fete nationale",
     ["Le nouvel an", "La fete des meres", "La fete du cacao"], "Le 20 mai est la fete nationale."),
    ("Quelle couleur figure au centre du drapeau camerounais ?", "Le rouge",
     ["Le bleu", "Le noir", "Le blanc"], "La bande rouge occupe le centre du drapeau."),
    ("Ou se trouve l'etoile du drapeau camerounais ?", "Sur la bande rouge centrale",
     ["Sur la bande verte", "Sur la bande jaune", "Dans un coin superieur"], "L'etoile d'or est au centre."),
    ("Quel animal donne son surnom a l'equipe nationale camerounaise ?", "Le lion",
     ["Le crocodile", "Le zebre", "Le chameau"], "Les Lions Indomptables."),
    ("Quelle est la principale ville de la region de l'Ouest ?", "Bafoussam",
     ["Douala", "Bertoua", "Maroua"], "Bafoussam est le chef-lieu de l'Ouest."),
    ("Quelle grande ville se trouve dans la region de l'Extreme-Nord ?", "Maroua",
     ["Kribi", "Buea", "Ebolowa"], "Maroua est le chef-lieu de l'Extreme-Nord."),
    ("Quelle ville est le chef-lieu de la region du Sud ?", "Ebolowa",
     ["Kribi", "Sangmelima", "Ambam"], "Ebolowa est le chef-lieu de la region du Sud."),
    ("Quelle ville universitaire anglophone se trouve au pied du mont Cameroun ?", "Buea",
     ["Bamenda", "Kumba", "Mamfe"], "L'Universite de Buea est installee au pied du volcan."),
    ("Quelle ville du Nord-Ouest est la plus grande de sa region ?", "Bamenda",
     ["Kumbo", "Wum", "Ndop"], "Bamenda est le chef-lieu du Nord-Ouest."),
    ("Comment appelle-t-on le repas a base de haricots ecrases cuits en feuilles ?", "Le koki",
     ["Le couscous", "Le riz cantonais", "La pizza"], "Le koki est prepare avec des haricots ecrases."),
    ("Avec quelle feuille prepare-t-on le plat national camerounais ?", "La feuille de ndole",
     ["La feuille de vigne", "La feuille de laurier", "La feuille de menthe"], "Le ndole doit son nom a cette feuille amere."),
    ("Quel accompagnement a base de manioc est vendu enveloppe dans des feuilles ?", "Le bobolo",
     ["Le pain de mie", "Le croissant", "La baguette viennoise"], "Le bobolo est un baton de manioc."),
    ("Quelle viande grillee epicee est typique du Nord du Cameroun ?", "Le soya",
     ["Le hamburger", "Le jambon de Parme", "Le saucisson sec"], "Le soya se vend en brochettes."),
    ("Quel plat associe poulet et banane plantain frite ?", "Le poulet DG",
     ["Le poulet basquaise", "Le poulet tandoori", "Le poulet au curry vert"], "Le poulet DG est un plat de fete."),
    ("Comment appelle-t-on les petits restaurants de rue tres populaires au Cameroun ?", "Les tourne-dos",
     ["Les brasseries etoilees", "Les cantines scolaires", "Les traiteurs de luxe"], "Le tourne-dos sert des repas rapides et bon marche."),
    ("Quelle organisation reunit les pays d'Afrique ?", "L'Union africaine",
     ["L'Union europeenne", "L'OTAN", "L'ASEAN"], "Le Cameroun est membre de l'Union africaine."),
    ("Quelle ville abrite le siege de l'Union africaine ?", "Addis-Abeba",
     ["Yaounde", "Douala", "Abuja"], "Le siege de l'UA est en Ethiopie."),
    ("Comment appelle-t-on l'ecole ou l'on passe le baccalaureat au Cameroun ?", "Le lycee",
     ["L'universite", "L'ecole maternelle", "Le centre de formation professionnelle uniquement"], "Le baccalaureat se prepare au lycee."),
    ("Quelle est la premiere langue apprise par la plupart des enfants camerounais a la maison ?",
     "Une langue nationale de leur communaute", ["Le latin", "Le grec ancien", "Le japonais"],
     "Les langues maternelles restent tres vivantes."),
    ("Quel objet du quotidien permet d'acheter du credit telephonique dans la rue ?", "Le call box",
     ["Le distributeur de billets", "La cabine telephonique europeenne", "Le guichet bancaire"],
     "Les call box sont presents a chaque coin de rue."),
    ("Quelle activite economique se pratique beaucoup sur la cote de Kribi et Limbe ?", "La peche",
     ["L'extraction de charbon", "La culture du ble d'hiver", "L'elevage de rennes"], "La peche artisanale est tres presente."),
    ("Quel materiau local est utilise pour fabriquer les paniers artisanaux ?", "Le raphia",
     ["Le plastique importe", "L'acier inoxydable", "Le verre souffle"], "Le raphia est tresse par les artisans."),
    ("Quel type de commerce domine dans les marches camerounais ?", "Le commerce de detail",
     ["Le commerce d'armement", "Le commerce d'avions", "Le commerce de satellites"], "Les marches sont domines par le detail."),
    ("Quelle est la plus grande richesse du Cameroun selon son slogan touristique ?", "Sa diversite",
     ["Son uniformite", "Sa petite taille", "Son isolement"], "La diversite culturelle et naturelle est mise en avant."),
    ("Combien de langues officielles le Cameroun possede-t-il ?", "Deux",
     ["Une", "Trois", "Cinq"], "Le francais et l'anglais."),
    ("Quelle ville camerounaise accueille le siege du gouvernement ?", "Yaounde",
     ["Douala", "Buea", "Bamenda"], "Les institutions sont a Yaounde."),
    ("Quel type d'entreprise est une boutique de quartier au Cameroun ?", "Une tres petite entreprise",
     ["Une multinationale", "Une banque centrale", "Une compagnie aerienne"], "Les boutiques de quartier sont des TPE."),
    ("Quelle est la principale source d'energie electrique du Cameroun ?", "L'hydroelectricite",
     ["L'energie nucleaire", "L'eolien offshore", "La geothermie"], "Les barrages fournissent l'essentiel de l'electricite."),
    ("Quel fleuve traverse la ville d'Edea et alimente un barrage ?", "La Sanaga",
     ["Le Nil", "Le Congo", "Le Niger"], "Edea est installee sur la Sanaga."),
    ("Comment appelle-t-on le chef de l'Etat camerounais ?", "Le president de la Republique",
     ["Le roi", "L'empereur", "Le chancelier"], "Le Cameroun est une republique."),
    ("Quelle assemblee vote les lois au Cameroun avec le Senat ?", "L'Assemblee nationale",
     ["Le Conseil constitutionnel", "La Cour supreme", "Le conseil municipal"], "Le Parlement comprend l'Assemblee nationale et le Senat."),
    ("Qui dirige une commune au Cameroun ?", "Le maire",
     ["Le prefet", "Le gouverneur", "Le ministre"], "Le maire est elu et dirige la commune."),
    ("Quel est le principal jour de repos hebdomadaire dans l'administration camerounaise ?", "Le dimanche",
     ["Le mardi", "Le jeudi", "Le lundi"], "Le week-end administratif comprend le samedi et le dimanche."),
    ("Quelle saison correspond aux fortes pluies dans le sud du Cameroun ?", "La saison des pluies",
     ["L'hiver enneige", "L'ete sec mediterraneen", "La periode de mousson asiatique"], "Le sud connait deux saisons de pluies."),
    ("Quel produit camerounais sert a fabriquer du chocolat ?", "Le cacao",
     ["Le coton", "Le mil", "Le riz"], "Le cacao est transforme en chocolat."),
    ("Quelle entreprise camerounaise transforme le cacao en chocolat et confiseries ?", "Chococam",
     ["ENEO", "CAMPOST", "CAMRAIL"], "Chococam produit notamment le chocolat Mambo."),
]


def build() -> list[Q]:
    qs: list[Q] = []
    for region, nb in NB_DEPTS.items():
        wrong = [str(n) for n in (2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12) if n != nb]
        qs.append(Q(
            f"Combien de departements compte la region : {region} ?",
            str(nb), wrong, MOYEN, "cameroun,geographie,regions",
            f"La region : {region} compte {nb} departements.",
        ))
    for pays, position in FRONTIERES.items():
        qs.append(Q(
            f"Ou se situe {pays} par rapport au Cameroun ?",
            position, others(pays, list(FRONTIERES.values())), MOYEN,
            "cameroun,geographie,frontieres", f"{cap(pays)} borde le Cameroun {position}.",
        ))
        qs.append(Q(
            f"Le Cameroun partage-t-il une frontiere terrestre avec {pays} ?",
            "Oui", ["Non, il en est separe par un ocean", "Non, il en est separe par un autre pays",
                    "Non, ce pays n'existe pas en Afrique"], FACILE,
            "cameroun,geographie,frontieres", f"{cap(pays)} est bien un voisin du Cameroun ({position}).",
        ))
    for question, correct, wrong, expl in FACILES:
        qs.append(Q(question, correct, wrong, FACILE, "cameroun,culture-generale", expl))
    return qs
