# -*- coding: utf-8 -*-
"""Banque Entrepreneuriat : entreprendre dans le contexte camerounais."""

from __future__ import annotations

from .common import CHALLENGE, FACILE, MOYEN, Q

CONTEXTE = [
    ("Ou un entrepreneur camerounais peut-il accomplir toutes ses formalites de creation en un seul lieu ?",
     "Au Centre de Formalites de Creation des Entreprises",
     ["A la sous-prefecture uniquement", "A la chefferie du quartier", "Au commissariat de police"],
     MOYEN, "Le CFCE regroupe les administrations concernees par la creation d'entreprise."),
    ("Quel numero identifie une entreprise camerounaise aupres de l'administration fiscale ?",
     "Le numero d'identifiant unique (NIU)", ["Le numero de telephone du gerant",
      "Le numero de plaque du vehicule", "Le numero de compte bancaire personnel"],
     MOYEN, "Le NIU figure sur la carte de contribuable."),
    ("Quel impot simplifie s'applique aux tres petites activites camerounaises ?", "L'impot libératoire",
     ["L'impot sur les grandes fortunes", "La taxe sur les vehicules de luxe", "L'impot sur les societes cotees"],
     MOYEN, "L'impot libératoire vise les petits contribuables."),
    ("Quel taux de TVA s'applique generalement au Cameroun ?", "19,25 %",
     ["5 %", "18 %", "25 %"], MOYEN, "17,5 % de TVA plus 10 % de centimes additionnels communaux."),
    ("Quelle agence publique camerounaise accompagne specifiquement les PME ?", "L'APME",
     ["La CONAC", "ELECAM", "L'ARMP"], MOYEN, "L'Agence de Promotion des PME accompagne les porteurs de projet."),
    ("Quelle banque publique camerounaise a ete creee pour financer les PME ?", "La BC-PME",
     ["La BEAC", "La Banque mondiale", "La BAD"], MOYEN, "La Banque Camerounaise des PME finance les petites structures."),
    ("Quel fonds public camerounais finance des formations et l'insertion professionnelle ?", "Le FNE",
     ["Le FMI", "Le PNUD", "L'UNESCO"], MOYEN, "Le Fonds National de l'Emploi soutient l'insertion et l'auto-emploi."),
    ("Quel programme camerounais appuie specifiquement les acteurs du secteur informel ?", "Le PIAASI",
     ["Le PNUD", "Le PAM", "L'UNICEF"], CHALLENGE, "Le Programme Integre d'Appui aux Acteurs du Secteur Informel."),
    ("Quelle organisation patronale represente les entreprises camerounaises ?", "Le GICAM",
     ["La CGT", "L'OIT", "La FIFA"], MOYEN, "Le Groupement Inter-patronal du Cameroun."),
    ("Quelle chambre consulaire delivre des services aux commercants camerounais ?", "La CCIMA",
     ["La CONAC", "La CNPS", "L'ANOR"], MOYEN, "Chambre de Commerce, d'Industrie, des Mines et de l'Artisanat."),
    ("Quel organisme camerounais definit les normes de qualite des produits ?", "L'ANOR",
     ["Le GICAM", "La CNPS", "ELECAM"], CHALLENGE, "L'Agence des Normes et de la Qualite."),
    ("A quel organisme un employeur camerounais declare-t-il ses salaries ?", "A la CNPS",
     ["A ELECAM", "A la CONAC", "A l'ANOR"], MOYEN, "La Caisse Nationale de Prevoyance Sociale."),
    ("Quel salon annuel de Yaounde met en valeur les entreprises camerounaises ?", "Promote",
     ["Le FESPACO", "Le SIAO", "Le Ngondo"], MOYEN, "Promote est un grand rendez-vous du secteur prive."),
    ("Quel service financier permet a un commercant camerounais d'encaisser sans compte bancaire classique ?",
     "Le mobile money", ["Le virement SWIFT uniquement", "Le cheque certifie uniquement",
      "La lettre de credit documentaire"], FACILE, "MTN MoMo et Orange Money sont largement utilises."),
    ("Quel avantage le mobile money apporte-t-il a une petite entreprise camerounaise ?",
     "Encaisser rapidement et garder une trace des transactions",
     ["Supprimer toutes les taxes", "Garantir des benefices", "Eviter de servir les clients"],
     FACILE, "Le mobile money securise et trace les encaissements."),
    ("Quel secteur est presente comme prioritaire par la strategie de developpement du Cameroun ?",
     "La transformation locale des produits agricoles",
     ["L'exploitation miniere sur la Lune", "La construction de fusees", "La production de neige"],
     MOYEN, "La SND30 mise sur l'industrialisation et la transformation locale."),
    ("Pourquoi la transformation locale du cacao est-elle une opportunite au Cameroun ?",
     "Parce qu'elle cree plus de valeur et d'emplois que l'exportation de feves brutes",
     ["Parce que le cacao ne se vend pas", "Parce que l'exportation est interdite",
      "Parce que la transformation coute moins cher que rien faire"], MOYEN,
     "Transformer sur place capte davantage de valeur ajoutee."),
    ("Quel frein est le plus souvent cite par les PME camerounaises ?", "L'acces au financement",
     ["L'exces de clients", "L'absence de concurrence", "Le trop grand nombre de banques"],
     FACILE, "Le financement reste la contrainte principale des PME."),
    ("Quel autre frein majeur les entrepreneurs camerounais citent-ils frequemment ?",
     "Le cout et la fiabilite de l'energie electrique",
     ["Le manque de terres agricoles partout", "L'interdiction de vendre en ligne",
      "L'absence de reseau telephonique dans les villes"], MOYEN,
     "Les coupures d'electricite pesent sur la production."),
    ("Quelle pratique traditionnelle camerounaise permet de financer un projet sans banque ?", "La tontine",
     ["L'introduction en bourse", "L'emprunt obligataire", "Le capital-risque international"],
     FACILE, "La tontine mobilise l'epargne collective."),
    ("Quel avantage un entrepreneur camerounais tire-t-il de la ZLECAf ?",
     "Un acces facilite aux marches des autres pays africains",
     ["Une exoneration totale d'impots a vie", "Une garantie de benefices",
      "Une interdiction d'exporter"], MOYEN, "La zone de libre-echange continentale ouvre le marche africain."),
    ("Quelle communaute economique facilite les echanges entre le Cameroun et ses voisins d'Afrique centrale ?",
     "La CEMAC", ["La CEDEAO", "L'ASEAN", "Le Mercosur"], MOYEN,
     "La CEMAC constitue un marche regional de plus de 50 millions d'habitants."),
    ("Quel secteur camerounais emploie le plus grand nombre de jeunes entrepreneurs informels ?",
     "Le commerce et les services de proximite",
     ["L'aeronautique", "La recherche spatiale", "L'industrie pharmaceutique lourde"],
     FACILE, "Commerce, restauration et transport dominent l'auto-emploi."),
    ("Pourquoi la creation d'une entreprise formelle facilite-t-elle l'acces aux marches publics ?",
     "Parce que les marches publics exigent des documents administratifs et fiscaux",
     ["Parce que l'Etat prefere les entreprises informelles", "Parce que la formalisation est gratuite",
      "Parce que les marches publics n'ont pas de regles"], MOYEN,
     "Attestations fiscales et immatriculation sont exigees."),
    ("Quel document camerounais atteste qu'une entreprise est a jour de ses obligations fiscales ?",
     "L'attestation de non-redevance", ["Le passeport du gerant", "La carte d'electeur",
      "L'acte de naissance"], CHALLENGE, "Elle est demandee pour les marches publics et certains credits."),
    ("Quelle culture d'exportation historique du Nord du Cameroun structure toute une filiere ?",
     "Le coton", ["Le cacao", "L'hevea", "La banane dessert"], MOYEN,
     "La SODECOTON encadre la filiere cotonniere."),
    ("Quel produit camerounais dispose d'une indication geographique protegee reconnue ?",
     "Le poivre de Penja", ["Le riz de Yagoua", "Le mais de Ndop", "L'ananas de Loum"],
     MOYEN, "Le poivre de Penja beneficie d'une IGP."),
    ("Quelle opportunite le port en eau profonde de Kribi ouvre-t-il aux entreprises ?",
     "Un acces logistique ameliore pour l'import-export",
     ["Une exoneration totale de TVA", "Une garantie de clients", "Une suppression des douanes"],
     MOYEN, "Kribi renforce la capacite portuaire nationale."),
    ("Pourquoi une jeune entreprise camerounaise a-t-elle interet a viser aussi la diaspora ?",
     "Parce que la diaspora represente un marche solvable et un relais de confiance",
     ["Parce que la diaspora ne consomme pas", "Parce que c'est obligatoire",
      "Parce que cela dispense d'etude de marche"], CHALLENGE,
     "Les transferts et la demande de la diaspora sont significatifs."),
    ("Quelle plateforme camerounaise a popularise la vente en ligne de produits varies ?", "Jumia",
     ["Le marche de Mokolo", "La CRTV", "CAMPOST"], FACILE, "Jumia est une place de marche en ligne implantee au Cameroun."),
    ("Quel avantage un entrepreneur tire-t-il d'une boutique en ligne au Cameroun ?",
     "Vendre au-dela de son quartier sans louer plusieurs locaux",
     ["Supprimer la concurrence", "Ne plus payer de fournisseurs", "Eviter toute logistique"],
     FACILE, "Le digital elargit la zone de chalandise."),
    ("Quelle contrainte logistique un e-commercant camerounais doit-il anticiper ?",
     "L'adressage imprecis et le cout de la livraison du dernier kilometre",
     ["L'absence totale de clients", "L'interdiction de livrer", "Le manque de motos dans le pays"],
     MOYEN, "Le dernier kilometre est un enjeu majeur en Afrique urbaine."),
    ("Quel mode de paiement rassure le plus les clients camerounais en e-commerce ?",
     "Le paiement a la livraison ou le mobile money",
     ["Le virement international uniquement", "Le paiement en cryptomonnaie exclusivement",
      "Le paiement par cheque uniquement"], MOYEN, "La confiance passe par le paiement a reception ou le mobile money."),
    ("Quelle competence est particulierement utile a un entrepreneur camerounais bilingue ?",
     "Pouvoir servir a la fois les marches francophone et anglophone",
     ["Pouvoir eviter les clients", "Pouvoir se passer de comptabilite",
      "Pouvoir ignorer la reglementation"], FACILE, "Le bilinguisme elargit le marche accessible."),
    ("Pourquoi les incubateurs se sont-ils multiplies a Douala et Yaounde ?",
     "Pour accompagner les jeunes porteurs de projet et structurer l'ecosysteme",
     ["Pour remplacer les universites", "Pour interdire les startups",
      "Pour collecter les impots"], MOYEN, "Les incubateurs offrent accompagnement, reseau et parfois financement."),
    ("Qu'est-ce qu'un espace de coworking apporte a un jeune entrepreneur ?",
     "Un lieu de travail equipe et un reseau, a cout partage",
     ["Un salaire garanti", "Des clients obligatoires", "Une exoneration fiscale"],
     FACILE, "Le coworking mutualise les couts fixes."),
    ("Quel secteur camerounais beneficie fortement de la croissance urbaine ?",
     "La restauration et les services de proximite",
     ["L'elevage de pingouins", "L'industrie du ski", "La peche polaire"],
     FACILE, "L'urbanisation cree une demande de services quotidiens."),
    ("Quelle activite agricole est souvent conseillee aux jeunes entrepreneurs ruraux camerounais ?",
     "L'agriculture de transformation et le maraichage a cycle court",
     ["La culture du ble d'hiver europeen", "L'elevage de rennes",
      "La production de vin de Bordeaux"], MOYEN, "Les cycles courts generent une tresorerie plus rapide."),
    ("Pourquoi l'agroalimentaire est-il considere comme un secteur porteur au Cameroun ?",
     "Parce que la production agricole est abondante mais peu transformee localement",
     ["Parce qu'il n'y a pas de clients", "Parce que la loi l'impose",
      "Parce que les matieres premieres sont importees"], MOYEN,
     "La transformation locale reste faible face au potentiel agricole."),
    ("Quel risque un entrepreneur prend-il en ne declarant pas son activite ?",
     "Rester bloque dans l'informel et s'exposer a des sanctions",
     ["Beneficier de credits bonifies", "Acceder aux marches publics",
      "Obtenir une subvention automatique"], MOYEN, "L'informalite limite la croissance et expose a des risques."),
]


def build() -> list[Q]:
    return [
        Q(question, correct, wrong, diff, "entrepreneuriat,cameroun", expl)
        for question, correct, wrong, diff, expl in CONTEXTE
    ]
