# -*- coding: utf-8 -*-
"""Banque Entrepreneuriat : glossaire des notions cles (2 angles par terme)."""

from __future__ import annotations

from .common import cap, CHALLENGE, FACILE, MOYEN, Q, others

# terme -> (definition, difficulte)
GLOSSAIRE = {
    "un entrepreneur": ("Une personne qui cree et dirige une activite economique en prenant des risques", FACILE),
    "un client": ("Une personne qui achete reellement le produit ou le service", FACILE),
    "un prospect": ("Une personne susceptible de devenir cliente mais qui n'a pas encore achete", MOYEN),
    "un fournisseur": ("Une entreprise ou une personne qui vend les matieres ou services dont on a besoin", FACILE),
    "un concurrent": ("Une entreprise qui propose une offre similaire aux memes clients", FACILE),
    "le chiffre d'affaires": ("Le total des ventes realisees sur une periode donnee", FACILE),
    "le benefice": ("Ce qui reste quand on retire toutes les charges du chiffre d'affaires", FACILE),
    "une charge": ("Une depense engagee pour faire fonctionner l'activite", FACILE),
    "la marge commerciale": ("La difference entre le prix de vente et le cout d'achat des marchandises", MOYEN),
    "le seuil de rentabilite": ("Le niveau de ventes a partir duquel l'entreprise ne perd plus d'argent", MOYEN),
    "la tresorerie": ("L'argent reellement disponible pour payer les depenses du moment", MOYEN),
    "le fonds de roulement": ("Les ressources stables qui financent le cycle d'exploitation", CHALLENGE),
    "le besoin en fonds de roulement": ("L'argent immobilise par les stocks et les creances clients", CHALLENGE),
    "un investissement": ("Une depense durable destinee a produire des revenus futurs", FACILE),
    "un business model": ("La facon dont l'entreprise cree de la valeur et gagne de l'argent", MOYEN),
    "un business plan": ("Le document qui presente le projet, le marche, la strategie et les previsions financieres", FACILE),
    "une etude de marche": ("La demarche qui consiste a analyser les clients, la concurrence et l'environnement", FACILE),
    "un MVP": ("Une premiere version simplifiee du produit servant a tester le marche", MOYEN),
    "un prototype": ("Une maquette fonctionnelle realisee avant la production en serie", MOYEN),
    "une proposition de valeur": ("La promesse claire de ce que le produit apporte au client", MOYEN),
    "un segment de clientele": ("Un groupe de clients qui partagent des besoins et comportements proches", MOYEN),
    "un persona": ("Le portrait type d'un client ideal utilise pour orienter l'offre", MOYEN),
    "le pitch": ("La presentation courte et convaincante d'un projet", FACILE),
    "l'elevator pitch": ("Une presentation du projet en moins d'une minute", MOYEN),
    "un incubateur": ("Une structure qui accompagne les porteurs de projet en phase de demarrage", MOYEN),
    "un accelerateur": ("Un programme intensif qui aide une jeune entreprise a croitre vite", MOYEN),
    "un mentor": ("Un entrepreneur experimente qui conseille un porteur de projet", FACILE),
    "un business angel": ("Un particulier qui investit son propre argent dans une jeune entreprise", MOYEN),
    "le capital-risque": ("Le financement par des fonds qui prennent des parts dans des entreprises a fort potentiel", CHALLENGE),
    "le crowdfunding": ("La collecte de fonds aupres d'un grand nombre de personnes via une plateforme", MOYEN),
    "la microfinance": ("Des services financiers de proximite destines aux petites activites", FACILE),
    "une tontine": ("Une epargne collective ou chaque membre recoit la cagnotte a tour de role", FACILE),
    "un apport personnel": ("La part d'argent que l'entrepreneur met lui-meme dans son projet", FACILE),
    "une subvention": ("Une aide financiere qui n'a pas a etre remboursee", MOYEN),
    "un pret bancaire": ("Une somme avancee par une banque et remboursee avec interets", FACILE),
    "un taux d'interet": ("Le cout du credit exprime en pourcentage du montant emprunte", FACILE),
    "un echeancier": ("Le calendrier des remboursements d'un credit", MOYEN),
    "une garantie": ("Un bien ou un engagement qui securise le preteur en cas de non-remboursement", MOYEN),
    "le capital social": ("Les ressources apportees par les associes a la creation de la societe", MOYEN),
    "un associe": ("Une personne qui detient des parts dans une societe", FACILE),
    "un actionnaire": ("Une personne qui detient des actions d'une societe anonyme", MOYEN),
    "un dividende": ("La part du benefice versee aux associes ou actionnaires", MOYEN),
    "une SARL": ("Une societe a responsabilite limitee, tres utilisee par les PME", MOYEN),
    "une SA": ("Une societe anonyme, adaptee aux projets de grande taille", MOYEN),
    "une entreprise individuelle": ("Une activite exercee en nom propre, sans creer de societe distincte", MOYEN),
    "un GIE": ("Un groupement d'interet economique qui met en commun des moyens", CHALLENGE),
    "une cooperative": ("Une organisation detenue et geree par ses membres pour leur benefice commun", MOYEN),
    "le RCCM": ("Le registre ou sont immatriculees les entreprises commerciales", MOYEN),
    "un statut juridique": ("La forme legale choisie pour exercer une activite", FACILE),
    "un contrat": ("Un accord qui engage juridiquement les parties", FACILE),
    "une facture": ("Le document qui detaille une vente et le montant a payer", FACILE),
    "un devis": ("Une proposition chiffree adressee au client avant la commande", FACILE),
    "un bon de commande": ("Le document par lequel un client confirme sa commande", MOYEN),
    "un recu": ("La preuve ecrite qu'un paiement a bien ete effectue", FACILE),
    "la comptabilite": ("L'enregistrement organise des operations financieres de l'entreprise", FACILE),
    "un bilan": ("Une photographie du patrimoine de l'entreprise a une date donnee", MOYEN),
    "un compte de resultat": ("Le document qui compare les produits et les charges d'un exercice", MOYEN),
    "un actif": ("Ce que l'entreprise possede", MOYEN),
    "un passif": ("Ce que l'entreprise doit", MOYEN),
    "l'amortissement": ("La constatation comptable de la perte de valeur d'un bien dans le temps", CHALLENGE),
    "une immobilisation": ("Un bien durable utilise plusieurs annees par l'entreprise", CHALLENGE),
    "un stock": ("L'ensemble des marchandises detenues et non encore vendues", FACILE),
    "une creance client": ("Une somme qu'un client doit encore a l'entreprise", MOYEN),
    "une dette fournisseur": ("Une somme que l'entreprise doit encore a un fournisseur", MOYEN),
    "la TVA": ("Une taxe sur la consommation collectee par l'entreprise pour l'Etat", MOYEN),
    "un impot": ("Un prelevement obligatoire verse a l'Etat", FACILE),
    "le marketing": ("L'ensemble des actions qui font connaitre, aimer et acheter une offre", FACILE),
    "le marketing mix": ("La combinaison produit, prix, distribution et communication", MOYEN),
    "le positionnement": ("La place que l'offre occupe dans l'esprit du client par rapport aux concurrents", MOYEN),
    "la segmentation": ("Le decoupage du marche en groupes de clients homogenes", MOYEN),
    "le ciblage": ("Le choix des segments de clients que l'on decide de servir", MOYEN),
    "une marque": ("Le signe distinctif qui identifie les produits d'une entreprise", FACILE),
    "un logo": ("Le symbole visuel qui represente la marque", FACILE),
    "l'image de marque": ("La perception que le public a de l'entreprise", MOYEN),
    "la fidelisation": ("L'ensemble des actions qui poussent un client a revenir acheter", MOYEN),
    "la prospection": ("La recherche active de nouveaux clients", MOYEN),
    "un canal de distribution": ("Le chemin par lequel le produit atteint le client", MOYEN),
    "le bouche-a-oreille": ("La recommandation spontanee d'un client a son entourage", FACILE),
    "une promotion": ("Une offre temporaire destinee a stimuler les ventes", FACILE),
    "une remise": ("Une reduction accordee sur le prix de vente", FACILE),
    "un avantage concurrentiel": ("Ce qui rend une offre durablement preferable a celle des concurrents", MOYEN),
    "une niche de marche": ("Un segment etroit et specialise peu couvert par les concurrents", MOYEN),
    "l'analyse SWOT": ("L'analyse des forces, faiblesses, opportunites et menaces", MOYEN),
    "une opportunite": ("Un element favorable de l'environnement que l'entreprise peut saisir", FACILE),
    "une menace": ("Un element defavorable de l'environnement qui peut nuire a l'activite", FACILE),
    "un risque": ("Un evenement incertain qui peut affecter le projet", FACILE),
    "un plan B": ("Une solution de rechange prevue si le plan initial echoue", FACILE),
    "la scalabilite": ("La capacite d'une activite a grandir sans que les couts augmentent proportionnellement", CHALLENGE),
    "le pivot": ("Le changement de direction strategique apres avoir teste le marche", MOYEN),
    "la traction": ("La preuve concrete que le marche adopte l'offre", CHALLENGE),
    "le taux de conversion": ("La part des visiteurs ou prospects qui deviennent clients", MOYEN),
    "le panier moyen": ("Le montant moyen depense par un client lors d'un achat", MOYEN),
    "un KPI": ("Un indicateur cle qui mesure la performance d'une activite", MOYEN),
    "un tableau de bord": ("Un outil de suivi qui reunit les indicateurs essentiels", MOYEN),
    "la productivite": ("Le rapport entre ce qui est produit et les moyens utilises", MOYEN),
    "la chaine de valeur": ("La suite des activites qui ajoutent de la valeur au produit final", CHALLENGE),
    "la logistique": ("L'organisation des flux de marchandises et d'informations", MOYEN),
    "un delai de livraison": ("Le temps entre la commande et la remise du produit au client", FACILE),
    "un partenaire cle": ("Un acteur externe indispensable au fonctionnement du modele economique", MOYEN),
    "un sous-traitant": ("Une entreprise a qui l'on confie une partie de la production", MOYEN),
    "la franchise": ("Le droit d'exploiter une marque et un savoir-faire contre une redevance", MOYEN),
    "une licence": ("L'autorisation d'utiliser un droit appartenant a un tiers", MOYEN),
    "un brevet": ("Un titre qui protege une invention technique", MOYEN),
    "la propriete intellectuelle": ("L'ensemble des droits qui protegent les creations de l'esprit", MOYEN),
    "l'OAPI": ("L'organisation africaine qui protege la propriete intellectuelle dans ses Etats membres", CHALLENGE),
    "un cahier des charges": ("Le document qui decrit precisement ce qui est attendu d'un projet", MOYEN),
    "un fournisseur strategique": ("Un fournisseur dont depend fortement la continuite de l'activite", CHALLENGE),
    "le service apres-vente": ("L'accompagnement du client apres l'achat", FACILE),
    "la satisfaction client": ("Le degre auquel l'offre repond aux attentes du client", FACILE),
    "une reclamation": ("L'expression d'un mecontentement par un client", FACILE),
    "un salarie": ("Une personne employee par l'entreprise en echange d'un salaire", FACILE),
    "un contrat de travail": ("L'accord qui lie l'employeur et le salarie", FACILE),
    "une fiche de poste": ("Le document qui decrit les missions et responsabilites d'un emploi", MOYEN),
    "le recrutement": ("Le processus de recherche et de selection des collaborateurs", FACILE),
    "la delegation": ("Le fait de confier une tache et l'autorite necessaire a quelqu'un d'autre", MOYEN),
    "le leadership": ("La capacite a inspirer et a entrainer une equipe vers un objectif", FACILE),
    "la motivation": ("Ce qui pousse une personne a s'engager et a fournir des efforts", FACILE),
    "un organigramme": ("La representation de l'organisation et des liens hierarchiques", MOYEN),
    "la gouvernance": ("L'ensemble des regles qui organisent la prise de decision dans l'entreprise", CHALLENGE),
    "un associe dormant": ("Un associe qui apporte des fonds sans participer a la gestion", CHALLENGE),
    "un pacte d'associes": ("Un accord qui organise les relations entre associes au-dela des statuts", CHALLENGE),
    "la levee de fonds": ("L'operation par laquelle une entreprise obtient des capitaux d'investisseurs", MOYEN),
    "la dilution": ("La reduction du pourcentage detenu par un associe apres une entree d'investisseurs", CHALLENGE),
    "la valorisation": ("L'estimation de la valeur financiere d'une entreprise", CHALLENGE),
    "le retour sur investissement": ("Le rapport entre le gain obtenu et la somme investie", MOYEN),
    "le cash-flow": ("Les flux d'argent qui entrent et sortent de l'entreprise", MOYEN),
    "un budget previsionnel": ("L'estimation chiffree des recettes et depenses a venir", MOYEN),
    "un plan de tresorerie": ("Le tableau qui prevoit mois par mois les entrees et sorties d'argent", CHALLENGE),
    "un compte bancaire professionnel": ("Un compte dedie a l'activite de l'entreprise", FACILE),
    "un fonds de commerce": ("L'ensemble des elements qui permettent d'exploiter une clientele", CHALLENGE),
    "un local commercial": ("L'espace physique ou l'entreprise recoit ses clients", FACILE),
    "un bail": ("Le contrat de location d'un local", MOYEN),
    "une assurance professionnelle": ("Un contrat qui couvre les risques lies a l'activite", MOYEN),
    "la responsabilite limitee": ("Le principe selon lequel l'associe ne perd que ses apports", MOYEN),
    "la responsabilite illimitee": ("Le principe selon lequel les biens personnels peuvent etre engages", CHALLENGE),
    "l'economie informelle": ("Les activites economiques exercees hors du cadre officiel enregistre", MOYEN),
    "la formalisation": ("Le passage d'une activite informelle a une activite enregistree", MOYEN),
    "une PME": ("Une petite ou moyenne entreprise", FACILE),
    "une startup": ("Une jeune entreprise innovante qui cherche un modele economique reproductible", FACILE),
    "un entrepreneur social": ("Une personne qui cree une activite pour resoudre un probleme social", MOYEN),
    "l'economie circulaire": ("Un modele qui reduit les dechets en reutilisant et recyclant les ressources", MOYEN),
    "le developpement durable": ("Un developpement qui repond aux besoins presents sans compromettre l'avenir", FACILE),
    "la RSE": ("La prise en compte des enjeux sociaux et environnementaux par l'entreprise", MOYEN),
    "une chaine d'approvisionnement": ("L'ensemble des etapes qui menent des matieres premieres au client", MOYEN),
    "l'export": ("La vente de produits ou services vers un autre pays", FACILE),
    "l'import": ("L'achat de produits ou services provenant d'un autre pays", FACILE),
    "une zone de libre-echange": ("Un espace ou les echanges entre pays membres sont facilites", MOYEN),
    "la ZLECAf": ("La zone de libre-echange continentale africaine", MOYEN),
    "un incoterm": ("Une regle internationale qui repartit les frais et risques entre vendeur et acheteur", CHALLENGE),
    "le benchmarking": ("La comparaison de ses pratiques avec celles des meilleurs du secteur", MOYEN),
    "la veille concurrentielle": ("La surveillance organisee de ce que font les concurrents", MOYEN),
    "un test utilisateur": ("Une observation de vrais utilisateurs face au produit", MOYEN),
    "une enquete terrain": ("La collecte d'informations directement aupres des personnes concernees", FACILE),
    "un questionnaire": ("Un outil structure de collecte de reponses aupres d'un echantillon", FACILE),
    "un echantillon": ("Le sous-ensemble de personnes interrogees pour representer une population", MOYEN),
    "le taux de marge": ("Le rapport entre la marge et le prix de vente, exprime en pourcentage", CHALLENGE),
    "le prix de revient": ("Le cout total supporte pour produire et vendre une unite", MOYEN),
    "un cout fixe": ("Une charge qui ne varie pas avec le volume d'activite", MOYEN),
    "un cout variable": ("Une charge qui evolue avec le volume produit ou vendu", MOYEN),
    "l'ecremage": ("Une strategie de prix eleve visant une clientele restreinte", CHALLENGE),
    "la penetration": ("Une strategie de prix bas visant a conquerir vite une large clientele", CHALLENGE),
    "un lead": ("Un contact commercial identifie et potentiellement interesse", MOYEN),
    "le tunnel de vente": ("Le parcours qui mene un prospect de la decouverte a l'achat", CHALLENGE),
    "un CRM": ("Un outil de gestion de la relation client", MOYEN),
    "l'inbound marketing": ("Une approche qui attire le client par du contenu utile plutot que par la publicite", CHALLENGE),
    "une campagne publicitaire": ("Un ensemble coordonne d'actions de communication payantes", FACILE),
    "un influenceur": ("Une personne dont l'audience peut recommander une offre", FACILE),
    "un partenariat": ("Un accord de cooperation entre deux organisations", FACILE),
    "un reseau professionnel": ("L'ensemble des relations utiles au developpement de l'activite", FACILE),
    "le networking": ("La construction volontaire d'un reseau de contacts professionnels", MOYEN),
    "une foire commerciale": ("Un evenement ou les entreprises exposent leurs produits", FACILE),
    "un appel d'offres": ("Une procedure de mise en concurrence pour attribuer un marche", MOYEN),
    "un marche public": ("Un contrat passe par une administration avec une entreprise", MOYEN),
    "la trace ecrite": ("La conservation de documents prouvant les operations realisees", MOYEN),
    "l'echec entrepreneurial": ("L'arret d'un projet qui n'a pas trouve son marche ou sa rentabilite", FACILE),
    "la resilience": ("La capacite a rebondir apres une difficulte", FACILE),
    "la gestion du temps": ("L'organisation des priorites pour utiliser efficacement ses journees", FACILE),
    "la procrastination": ("La tendance a repousser les taches importantes", FACILE),
    "un objectif SMART": ("Un objectif specifique, mesurable, atteignable, realiste et temporel", MOYEN),
    "un acompte": ("Une somme versee a la commande, avant la livraison complete", FACILE),
    "un solde": ("Le reste a payer apres deduction de l'acompte", MOYEN),
    "un delai de paiement": ("Le temps accorde au client pour regler sa facture", FACILE),
    "un impaye": ("Une facture arrivee a echeance et non reglee", MOYEN),
    "une relance": ("Le rappel adresse a un client qui n'a pas encore paye", FACILE),
    "un avoir": ("Un document qui annule ou reduit une facture deja emise", CHALLENGE),
    "un bon de livraison": ("Le document qui accompagne la marchandise remise au client", MOYEN),
    "un inventaire": ("Le comptage physique des marchandises detenues", MOYEN),
    "la rotation des stocks": ("La vitesse a laquelle le stock se renouvelle par les ventes", CHALLENGE),
    "une rupture de stock": ("La situation ou un produit demande n'est plus disponible", FACILE),
    "un fournisseur agree": ("Un fournisseur selectionne selon des criteres de qualite et de fiabilite", CHALLENGE),
    "un appel a projets": ("Une procedure qui invite les porteurs de projet a candidater pour un appui", MOYEN),
    "un pitch deck": ("La presentation visuelle d'un projet destinee aux investisseurs", MOYEN),
    "une due diligence": ("L'audit approfondi realise par un investisseur avant d'entrer au capital", CHALLENGE),
    "un actionnariat salarie": ("Le fait d'associer les employes au capital de l'entreprise", CHALLENGE),
    "un plan de croissance": ("La feuille de route qui organise le developpement de l'activite", MOYEN),
    "la diversification": ("Le fait d'elargir son offre ou ses marches pour repartir les risques", MOYEN),
    "l'internationalisation": ("Le developpement de l'activite au-dela des frontieres nationales", MOYEN),
    "une alliance strategique": ("Un accord durable entre entreprises pour atteindre un objectif commun", CHALLENGE),
    "une fusion": ("Le regroupement de deux entreprises en une seule entite", MOYEN),
    "une acquisition": ("Le rachat d'une entreprise par une autre", MOYEN),
    "la cession d'entreprise": ("La vente de l'entreprise a un repreneur", MOYEN),
    "la transmission": ("Le passage de l'entreprise a un successeur, souvent familial", MOYEN),
    "la faillite": ("La situation ou l'entreprise ne peut plus faire face a ses dettes", FACILE),
    "la liquidation": ("La procedure de vente des actifs pour rembourser les creanciers", CHALLENGE),
    "un audit": ("Un examen independant des comptes ou des processus de l'entreprise", MOYEN),
    "un expert-comptable": ("Un professionnel qui tient ou controle la comptabilite de l'entreprise", FACILE),
    "un commissaire aux comptes": ("Un professionnel qui certifie la regularite des comptes annuels", CHALLENGE),
    "un exercice comptable": ("La periode, generalement de douze mois, couverte par les comptes annuels", MOYEN),
    "la valeur ajoutee": ("La richesse creee par l'entreprise au-dela de ce qu'elle achete a l'exterieur", CHALLENGE),
    "la productivite du travail": ("La production obtenue rapportee au temps de travail utilise", CHALLENGE),
    "un indicateur de satisfaction": ("Une mesure du contentement des clients apres achat", MOYEN),
    "un fichier client": ("La base regroupant les coordonnees et l'historique des clients", FACILE),
    "la prospection telephonique": ("La recherche de clients par appels directs", MOYEN),
    "un salon professionnel": ("Un evenement ou les entreprises d'un secteur exposent et rencontrent des clients", FACILE),
    "un franchise": ("Une entreprise qui exploite la marque et le savoir-faire d'un franchiseur", CHALLENGE),
}


def build() -> list[Q]:
    qs: list[Q] = []
    definitions = [v[0] for v in GLOSSAIRE.values()]
    termes = list(GLOSSAIRE.keys())
    for terme, (definition, diff) in GLOSSAIRE.items():
        qs.append(Q(
            f"En entrepreneuriat, que designe {terme} ?",
            definition, others(terme, definitions), diff, "entrepreneuriat,glossaire",
            f"{cap(terme)} : {definition.lower()}.",
        ))
        qs.append(Q(
            f"Comment appelle-t-on ceci : {definition} ?",
            terme, others(definition, termes), diff, "entrepreneuriat,glossaire",
            f"Il s'agit de {terme}.",
        ))
    return qs
