# -*- coding: utf-8 -*-
"""Banque Entrepreneuriat : marketing, vente, gestion, juridique et financement."""

from __future__ import annotations

from .common import CHALLENGE, FACILE, MOYEN, Q

MARKETING = [
    ("Que designe le premier P du marketing mix ?", "Le produit",
     ["Le personnel", "Le partenaire", "Le pouvoir"], FACILE, "Les 4P sont produit, prix, place et promotion."),
    ("Combien de composantes classiques compte le marketing mix ?", "Quatre",
     ["Deux", "Six", "Dix"], FACILE, "Produit, prix, distribution et communication."),
    ("Que signifie le P de place dans le marketing mix ?", "La distribution, c'est-a-dire la facon dont le produit atteint le client",
     ["Le lieu de naissance du fondateur", "La place de l'entreprise en bourse", "L'emplacement du siege social uniquement"],
     MOYEN, "Place designe les canaux de distribution."),
    ("Quel est le but principal d'une etude de marche ?", "Verifier qu'il existe une demande reelle et solvable",
     ["Decorer le business plan", "Faire plaisir a la banque", "Choisir la couleur du logo"],
     FACILE, "L'etude de marche teste l'existence et la taille de la demande."),
    ("Quelle question un entrepreneur doit-il se poser en premier avant de creer son produit ?",
     "Quel probleme reel est-ce que je resous, et pour qui ?",
     ["Quelle sera la couleur de mon logo ?", "Combien de bureaux vais-je louer ?",
      "Quel nom sonne le mieux en anglais ?"], FACILE, "Le probleme client precede la solution."),
    ("Qu'est-ce qu'un client fidele apporte a une entreprise ?", "Des achats repetes et des recommandations",
     ["Uniquement des reclamations", "Une baisse automatique des couts fixes", "Une exoneration d'impots"],
     FACILE, "Fideliser coute moins cher que conquerir."),
    ("Pourquoi dit-on qu'il coute plus cher de gagner un nouveau client que d'en garder un ?",
     "Parce que la prospection demande plus d'efforts et de depenses que la fidelisation",
     ["Parce que les nouveaux clients paient moins", "Parce que la loi l'impose",
      "Parce que les anciens clients ne consomment plus"], MOYEN, "La fidelisation optimise le cout d'acquisition."),
    ("Que mesure le taux de conversion d'une boutique en ligne ?", "La part des visiteurs qui deviennent acheteurs",
     ["Le nombre total de visiteurs", "La vitesse du site", "Le nombre de produits en stock"],
     MOYEN, "Conversion = acheteurs / visiteurs."),
    ("Quel canal de communication est le moins couteux pour une tres petite entreprise qui demarre ?",
     "Le bouche-a-oreille et les reseaux sociaux",
     ["Un spot televise national", "Une campagne d'affichage 4x3 dans tout le pays",
      "Une page entiere dans un magazine international"], FACILE, "Les canaux gratuits ou peu couteux conviennent au demarrage."),
    ("Qu'est-ce qu'un avantage concurrentiel durable ?", "Un atout difficile a copier par les concurrents",
     ["Une promotion valable une journee", "Un prix bas temporaire", "Un local plus grand"],
     MOYEN, "La durabilite vient de la difficulte d'imitation."),
    ("Que veut dire se positionner sur une niche ?", "Servir un segment etroit avec une offre tres adaptee",
     ["Vendre a tout le monde le meme produit", "Copier le leader du marche",
      "Baisser ses prix au maximum"], MOYEN, "La niche permet d'eviter la concurrence frontale."),
    ("Quel est l'objectif d'une promotion commerciale ?", "Stimuler les ventes sur une periode limitee",
     ["Reduire durablement la valeur percue", "Faire fuir les clients", "Augmenter les charges fixes"],
     FACILE, "La promotion est une action ponctuelle."),
    ("Pourquoi faut-il eviter les promotions permanentes ?", "Parce qu'elles detruisent la valeur percue et la marge",
     ["Parce que la loi les interdit", "Parce qu'elles attirent trop de clients",
      "Parce qu'elles augmentent les stocks"], CHALLENGE, "Une remise permanente devient le prix de reference."),
    ("Quelle information est la plus utile pour ameliorer une offre ?", "Les retours des clients qui n'ont pas achete",
     ["Le nombre d'abonnes sur les reseaux", "L'avis du meilleur ami du fondateur",
      "La superficie du local"], CHALLENGE, "Comprendre les refus revele les freins a l'achat."),
    ("Qu'est-ce qu'un persona en marketing ?", "Le portrait detaille d'un client type",
     ["Un logiciel comptable", "Un statut juridique", "Un mode de financement"],
     MOYEN, "Le persona guide les decisions produit et communication."),
    ("Que designe le positionnement d'une marque ?", "La place qu'elle occupe dans l'esprit du client face aux concurrents",
     ["Sa position geographique", "Son rang au registre du commerce", "Son classement fiscal"],
     MOYEN, "Le positionnement est une perception, pas un lieu."),
    ("Pourquoi une entreprise doit-elle surveiller ses concurrents ?", "Pour ajuster son offre et anticiper les evolutions du marche",
     ["Pour copier exactement leurs produits", "Pour porter plainte systematiquement",
      "Pour fixer ses prix au hasard"], FACILE, "La veille concurrentielle nourrit la strategie."),
    ("Que signifie fideliser un client ?", "Faire en sorte qu'il revienne acheter regulierement",
     ["Le forcer a signer un contrat a vie", "Lui interdire d'aller ailleurs",
      "Ne plus jamais le contacter"], FACILE, "La fidelisation repose sur la satisfaction."),
    ("Quel outil permet de suivre les echanges avec chaque client ?", "Un CRM",
     ["Un tableur de paie", "Un logiciel de dessin", "Une imprimante"],
     MOYEN, "Le CRM centralise l'historique de la relation client."),
    ("Quelle strategie de prix consiste a entrer sur le marche avec un prix bas pour gagner vite des clients ?",
     "La strategie de penetration", ["La strategie d'ecremage", "La strategie de niche",
      "La strategie de diversification"], CHALLENGE, "La penetration vise le volume."),
    ("Quelle strategie de prix consiste a vendre cher a une clientele restreinte ?", "La strategie d'ecremage",
     ["La strategie de penetration", "La strategie de discount", "La strategie de dumping"],
     CHALLENGE, "L'ecremage cible une clientele prete a payer plus."),
    ("Que faut-il verifier avant de baisser ses prix pour repondre a un concurrent ?",
     "Que la marge restante permet toujours de couvrir les charges",
     ["Que le concurrent est d'accord", "Que les clients ne s'en apercoivent pas",
      "Que le local est assez grand"], MOYEN, "Une baisse de prix se calcule, elle ne s'improvise pas."),
    ("Quel est le role d'un slogan ?", "Resumer en quelques mots la promesse de la marque",
     ["Decrire la comptabilite de l'entreprise", "Lister les statuts juridiques",
      "Remplacer le business plan"], FACILE, "Le slogan porte la promesse."),
    ("Pourquoi un entrepreneur doit-il connaitre son cout d'acquisition client ?",
     "Pour verifier que gagner un client coute moins que ce qu'il rapporte",
     ["Pour payer plus d'impots", "Pour recruter plus vite", "Pour choisir son statut juridique"],
     CHALLENGE, "Le CAC doit rester inferieur a la valeur vie client."),
    ("Que designe la valeur vie client ?", "Le total des marges generees par un client sur toute la duree de la relation",
     ["Le prix du premier achat uniquement", "L'age moyen des clients",
      "Le nombre de clients par jour"], CHALLENGE, "La LTV justifie l'investissement en acquisition."),
]

GESTION = [
    ("Pourquoi separer le compte bancaire de l'entreprise de son compte personnel ?",
     "Pour connaitre la rentabilite reelle de l'activite et faciliter la gestion",
     ["Pour payer plus de frais bancaires", "Parce que la banque l'impose toujours",
      "Pour cacher des operations"], FACILE, "La separation des comptes est une base de la gestion."),
    ("Quel document permet de savoir si l'entreprise gagne ou perd de l'argent sur une periode ?",
     "Le compte de resultat", ["Le bail commercial", "Le registre du personnel", "Le devis"],
     MOYEN, "Le compte de resultat compare produits et charges."),
    ("Quel document presente ce que l'entreprise possede et ce qu'elle doit ?", "Le bilan",
     ["Le compte de resultat", "Le catalogue produits", "Le contrat de travail"],
     MOYEN, "Le bilan est une photographie du patrimoine."),
    ("Une entreprise peut-elle etre rentable et manquer quand meme de tresorerie ?",
     "Oui, si les clients paient tard et les charges tombent tot",
     ["Non, c'est impossible", "Oui, uniquement si elle fraude",
      "Non, sauf en cas de vol"], MOYEN, "Rentabilite et tresorerie sont deux notions distinctes."),
    ("Quelle est la premiere cause d'echec des jeunes entreprises ?",
     "Un marche insuffisant ou mal compris, souvent double de problemes de tresorerie",
     ["Un logo mal dessine", "Un local trop petit", "Un nom d'entreprise trop court"],
     MOYEN, "L'absence de demande reelle et les tensions de tresorerie dominent les causes d'echec."),
    ("Que permet un budget previsionnel ?", "Anticiper les recettes et les depenses a venir",
     ["Enregistrer le passe uniquement", "Remplacer les factures", "Fixer les impots de l'Etat"],
     MOYEN, "Le previsionnel sert a piloter, pas seulement a constater."),
    ("Pourquoi tenir un inventaire regulier de ses stocks ?", "Pour detecter les pertes et ajuster les commandes",
     ["Pour occuper les employes", "Pour augmenter les prix automatiquement",
      "Pour eviter de payer les fournisseurs"], MOYEN, "L'inventaire fiabilise la gestion."),
    ("Que signifie deleguer efficacement ?", "Confier une tache avec les moyens, l'autorite et un suivi clairs",
     ["Se debarrasser d'une tache sans explication", "Faire tout soi-meme",
      "Donner des ordres contradictoires"], MOYEN, "Deleguer suppose clarte et suivi."),
    ("Quel est le risque de tout vouloir faire soi-meme dans une entreprise qui grandit ?",
     "Devenir un goulot d'etranglement et freiner la croissance",
     ["Economiser durablement sur tout", "Ameliorer la qualite de chaque tache",
      "Motiver automatiquement l'equipe"], MOYEN, "Le fondateur devient le frein principal."),
    ("Quelle methode aide a prioriser les taches selon l'urgence et l'importance ?", "La matrice d'Eisenhower",
     ["Le bilan comptable", "L'analyse PESTEL", "Le compte de resultat"],
     CHALLENGE, "La matrice urgent/important structure les priorites."),
    ("Que designe un objectif SMART ?", "Un objectif specifique, mesurable, atteignable, realiste et temporel",
     ["Un objectif secret", "Un objectif fixe par la banque", "Un objectif sans echeance"],
     MOYEN, "SMART est un acronyme de qualite d'objectif."),
    ("Pourquoi un entrepreneur doit-il suivre quelques indicateurs cles plutot que des dizaines ?",
     "Pour rester concentre sur ce qui influence reellement la performance",
     ["Parce que compter est interdit", "Pour cacher les mauvais chiffres",
      "Parce que les indicateurs coutent cher"], MOYEN, "Trop d'indicateurs tue la decision."),
    ("Quel comportement traduit une bonne gestion des risques ?", "Identifier les risques majeurs et prevoir des solutions de repli",
     ["Ignorer les risques pour rester optimiste", "Arreter toute activite risquee",
      "Attendre la crise pour reagir"], MOYEN, "Anticiper vaut mieux que subir."),
    ("Quel est l'interet d'un tableau de bord mensuel ?", "Detecter tot les ecarts et corriger rapidement",
     ["Impressionner les visiteurs", "Remplacer la comptabilite legale",
      "Justifier une augmentation de prix"], MOYEN, "Le pilotage regulier permet la correction rapide."),
    ("Pourquoi conserver ses factures et justificatifs ?", "Pour prouver les operations et tenir une comptabilite fiable",
     ["Pour decorer le bureau", "Parce que le client l'exige toujours",
      "Pour augmenter le chiffre d'affaires"], FACILE, "Les justificatifs sont la base de la preuve comptable."),
    ("Quelle attitude adopter face a un employe qui commet une erreur honnete ?",
     "Corriger, expliquer et transformer l'erreur en apprentissage",
     ["Le licencier immediatement", "L'humilier devant l'equipe", "Ignorer completement l'erreur"],
     FACILE, "Le droit a l'erreur encadre developpe les competences."),
    ("Quel document precise les missions attendues d'un collaborateur ?", "La fiche de poste",
     ["Le bilan", "Le devis", "Le registre du commerce"], MOYEN, "La fiche de poste clarifie le role."),
    ("Que designe la culture d'entreprise ?", "L'ensemble des valeurs et comportements partages dans l'organisation",
     ["Le nombre de diplomes des employes", "Le montant du capital social",
      "La superficie des bureaux"], MOYEN, "La culture oriente les comportements au quotidien."),
    ("Pourquoi les reunions doivent-elles avoir un ordre du jour ?", "Pour rester efficaces et deboucher sur des decisions",
     ["Pour durer plus longtemps", "Pour eviter de prendre des decisions",
      "Parce que la loi l'impose"], FACILE, "Un ordre du jour cadre la reunion."),
    ("Quel est l'interet de documenter ses procedures ?", "Permettre a l'activite de fonctionner sans dependre d'une seule personne",
     ["Compliquer le travail", "Augmenter les charges fixes", "Ralentir la production"],
     CHALLENGE, "La documentation rend l'entreprise transmissible."),
]

JURIDIQUE = [
    ("Quelle forme juridique limite la responsabilite des associes a leurs apports ?", "La SARL",
     ["L'entreprise individuelle", "La societe en nom collectif", "L'association de fait"],
     MOYEN, "La responsabilite limitee protege le patrimoine personnel."),
    ("Dans une entreprise individuelle, quel est le principal risque pour l'entrepreneur ?",
     "Son patrimoine personnel peut etre engage en cas de dettes",
     ["Il ne peut jamais faire de benefice", "Il ne peut pas embaucher",
      "Il ne peut pas ouvrir de compte bancaire"], MOYEN, "L'entreprise individuelle n'a pas de personnalite distincte."),
    ("Quel organisme immatricule les societes commerciales dans l'espace OHADA ?", "Le RCCM",
     ["Le cadastre", "L'etat civil", "La chambre d'agriculture"], MOYEN,
     "Le Registre du Commerce et du Credit Mobilier."),
    ("Combien d'Etats membres compte l'OHADA ?", "17",
     ["8", "12", "27"], CHALLENGE, "L'OHADA regroupe 17 Etats africains."),
    ("Que harmonise l'OHADA ?", "Le droit des affaires dans ses Etats membres",
     ["Les programmes scolaires", "Les regles sportives", "Les tarifs douaniers mondiaux"],
     MOYEN, "L'OHADA unifie le droit commercial et des societes."),
    ("Quel referentiel comptable les entreprises de l'espace OHADA appliquent-elles ?", "Le SYSCOHADA",
     ["Le plan comptable general francais", "Les US GAAP", "Le plan comptable chinois"],
     CHALLENGE, "Le SYSCOHADA revise est en vigueur depuis 2018."),
    ("Que doit contenir au minimum une facture commerciale ?",
     "L'identite des parties, la description, les quantites, les prix et la date",
     ["Uniquement le montant", "Uniquement le nom du vendeur", "Uniquement la date"],
     MOYEN, "Une facture incomplete n'a pas de valeur probante."),
    ("Quelle est la difference entre un devis et une facture ?",
     "Le devis est une proposition avant la vente, la facture constate la vente",
     ["Il n'y a aucune difference", "Le devis se paie, pas la facture",
      "La facture precede toujours le devis"], FACILE, "Le devis engage sur un prix, la facture sur un du."),
    ("Que se passe-t-il si une entreprise exerce sans immatriculation ?",
     "Elle reste dans l'informel et s'expose a des sanctions et a des blocages commerciaux",
     ["Elle beneficie d'avantages fiscaux", "Elle obtient plus facilement des credits",
      "Elle accede automatiquement aux marches publics"], MOYEN, "L'absence d'immatriculation ferme de nombreuses portes."),
    ("Pourquoi proteger sa marque aupres de l'organisme competent ?",
     "Pour empecher un tiers de l'utiliser et securiser son identite commerciale",
     ["Pour payer plus d'impots", "Pour obliger les clients a acheter",
      "Pour eviter de tenir une comptabilite"], MOYEN, "L'enregistrement confere un droit exclusif."),
    ("Quel organisme protege les marques et brevets dans plusieurs pays africains francophones ?", "L'OAPI",
     ["L'OMS", "L'UNESCO", "La FAO"], MOYEN, "L'Organisation Africaine de la Propriete Intellectuelle."),
    ("Quel type de contrat lie une entreprise a un salarie ?", "Le contrat de travail",
     ["Le bail commercial", "Le contrat de franchise", "Le contrat d'assurance auto"],
     FACILE, "Le contrat de travail encadre la relation employeur-salarie."),
    ("Que doit faire un employeur lorsqu'il embauche un salarie ?",
     "Le declarer aupres de l'organisme de securite sociale competent",
     ["Ne rien declarer", "Attendre un an avant toute demarche",
      "Declarer uniquement s'il le souhaite"], MOYEN, "La declaration protege le salarie et l'employeur."),
    ("Qu'est-ce qu'un bail commercial ?", "Le contrat de location d'un local destine a une activite commerciale",
     ["Un pret bancaire", "Une assurance vie", "Un contrat de vente de marchandises"],
     MOYEN, "Le bail encadre l'occupation du local."),
    ("Quel document formalise les regles de fonctionnement d'une societe ?", "Les statuts",
     ["La facture", "Le bon de livraison", "Le catalogue produits"],
     MOYEN, "Les statuts organisent la vie sociale de l'entreprise."),
    ("Que prevoit un pacte d'associes ?", "Les regles de relation entre associes au-dela des statuts",
     ["Le montant des salaires des clients", "Le prix de vente des produits",
      "Le calendrier des livraisons"], CHALLENGE, "Le pacte anticipe les conflits entre associes."),
    ("Que se passe-t-il en cas de non-respect d'un contrat commercial ?",
     "La partie lesee peut demander l'execution ou des dommages et interets",
     ["Rien du tout", "Le contrat devient automatiquement gratuit",
      "L'entreprise est dissoute d'office"], MOYEN, "L'inexecution ouvre droit a reparation."),
    ("Pourquoi lire attentivement les conditions d'un contrat de credit ?",
     "Pour connaitre le taux reel, les frais et les garanties exigees",
     ["Pour perdre du temps", "Parce que le banquier l'exige",
      "Pour eviter de rembourser"], FACILE, "Les clauses determinent le cout reel du credit."),
]

FINANCEMENT = [
    ("Quelle source de financement ne demande aucun remboursement ?", "La subvention",
     ["Le pret bancaire", "Le credit fournisseur", "Le credit-bail"],
     MOYEN, "La subvention est une aide non remboursable."),
    ("Qu'est-ce que le financement par fonds propres ?", "L'argent apporte par l'entrepreneur et les associes",
     ["Un pret de la banque", "Une avance des clients", "Un decouvert bancaire"],
     MOYEN, "Les fonds propres n'ont pas d'echeance de remboursement."),
    ("Pourquoi une banque demande-t-elle un apport personnel ?", "Pour verifier l'engagement de l'entrepreneur et partager le risque",
     ["Pour reduire ses benefices", "Parce que la loi l'interdit autrement",
      "Pour eviter d'accorder le credit"], MOYEN, "L'apport temoigne de l'implication du porteur de projet."),
    ("Qu'est-ce qu'un business angel ?", "Un particulier qui investit son propre argent dans une jeune entreprise",
     ["Un salarie de banque", "Un inspecteur des impots", "Un fournisseur exclusif"],
     MOYEN, "Le business angel apporte capital et reseau."),
    ("Que cede une entreprise lors d'une levee de fonds en capital ?", "Une part de son capital aux investisseurs",
     ["Ses locaux", "Ses stocks", "Ses salaries"], MOYEN, "L'investisseur devient associe."),
    ("Quel inconvenient presente une levee de fonds importante pour le fondateur ?", "La dilution de sa part dans le capital",
     ["L'obligation de fermer", "L'interdiction de vendre", "La perte de sa clientele"],
     CHALLENGE, "Plus on leve, plus la part relative du fondateur diminue."),
    ("Qu'est-ce que le crowdfunding ?", "La collecte de petites sommes aupres d'un grand nombre de contributeurs",
     ["Un pret bancaire classique", "Une subvention d'Etat", "Une avance sur salaire"],
     MOYEN, "Le financement participatif passe par des plateformes en ligne."),
    ("Quel role joue la microfinance pour les petits entrepreneurs ?",
     "Offrir des credits et de l'epargne adaptes aux petites activites",
     ["Financer uniquement les multinationales", "Remplacer l'administration fiscale",
      "Distribuer des subventions internationales"], FACILE, "La microfinance sert les exclus du systeme bancaire classique."),
    ("Quel est l'avantage principal d'une tontine pour un entrepreneur ?",
     "Acceder rapidement a une somme importante grace a l'epargne collective",
     ["Ne jamais rembourser", "Payer moins d'impots", "Obtenir un local gratuit"],
     FACILE, "La tontine mobilise l'epargne du groupe."),
    ("Quel est le risque d'un financement uniquement par credit a court terme ?",
     "Devoir rembourser avant que l'activite ne genere assez de revenus",
     ["Payer moins d'interets", "Obtenir automatiquement une subvention",
      "Augmenter la duree du credit"], CHALLENGE, "L'horizon du financement doit correspondre a celui du projet."),
    ("Qu'est-ce que le credit fournisseur ?", "Le delai de paiement accorde par un fournisseur",
     ["Un pret accorde par un client", "Une subvention de l'Etat", "Une action en bourse"],
     MOYEN, "Le credit fournisseur finance le cycle d'exploitation."),
    ("Qu'est-ce que le credit-bail (leasing) ?", "La location d'un equipement avec option d'achat a la fin",
     ["Un don d'equipement", "Un pret sans interet", "Une vente immediate"],
     CHALLENGE, "Le leasing evite d'immobiliser la tresorerie."),
    ("Que verifie principalement un investisseur avant de financer une jeune entreprise ?",
     "La qualite de l'equipe, le marche et les premieres preuves de traction",
     ["La couleur du logo", "Le nombre d'annees d'etudes du fondateur uniquement",
      "La taille du bureau"], MOYEN, "Equipe, marche et traction sont les criteres cles."),
    ("Pourquoi un entrepreneur doit-il connaitre son besoin de financement precis ?",
     "Pour demander ni trop ni trop peu et rester credible",
     ["Pour impressionner ses amis", "Pour eviter de tenir une comptabilite",
      "Pour payer moins d'impots"], MOYEN, "Un besoin chiffre credibilise la demande."),
    ("Que finance-t-on avec un credit d'investissement ?", "Des biens durables comme des machines ou un vehicule",
     ["Les salaires du mois", "L'achat de matieres consommees immediatement",
      "Le paiement des factures d'electricite"], MOYEN, "Les investissements se financent a moyen ou long terme."),
    ("Que finance-t-on avec un credit de tresorerie ?", "Les besoins courants a court terme",
     ["La construction d'une usine", "L'achat d'un terrain", "Une acquisition d'entreprise"],
     MOYEN, "Le credit de tresorerie couvre les decalages de court terme."),
    ("Quel document une banque demande-t-elle systematiquement pour un dossier de credit ?",
     "Un plan d'affaires avec des previsions financieres",
     ["Une photo de famille", "Un certificat de bonne conduite sportive",
      "Un diplome de langue etrangere"], FACILE, "Le business plan structure l'analyse du risque."),
    ("Qu'est-ce qu'une garantie dans un dossier de credit ?",
     "Un bien ou un engagement qui protege le preteur en cas de defaut",
     ["Une promesse verbale sans valeur", "Une reduction du taux d'interet",
      "Un cadeau offert par la banque"], MOYEN, "La garantie couvre le risque du preteur."),
]


def build() -> list[Q]:
    qs: list[Q] = []
    for bloc, tag in ((MARKETING, "entrepreneuriat,marketing"),
                      (GESTION, "entrepreneuriat,gestion"),
                      (JURIDIQUE, "entrepreneuriat,juridique"),
                      (FINANCEMENT, "entrepreneuriat,financement")):
        for question, correct, wrong, diff, expl in bloc:
            qs.append(Q(question, correct, wrong, diff, tag, expl))
    return qs
