# -*- coding: utf-8 -*-
"""Banque Entrepreneuriat : mises en situation et raisonnement entrepreneurial."""

from __future__ import annotations

from .common import CHALLENGE, FACILE, MOYEN, Q

# (situation, bonne reponse, [mauvaises], difficulte, explication)
SCENARIOS = [
    ("Un entrepreneur constate que les etudiants ont du mal a trouver un logement. Quelle est la premiere demarche la plus pertinente ?",
     "Interroger les etudiants pour comprendre precisement leurs besoins",
     ["Developper immediatement une application mobile", "Acheter un serveur puissant", "Commander un logo professionnel"],
     FACILE, "On valide le probleme aupres des utilisateurs avant d'investir."),
    ("Vous disposez de 100 000 FCFA pour lancer une petite activite. Que faites-vous en premier ?",
     "Etudier les besoins des clients de votre quartier",
     ["Acheter le maximum de marchandises", "Louer un grand bureau", "Imprimer 10 000 flyers"],
     FACILE, "Comprendre la demande evite d'immobiliser son argent inutilement."),
    ("Votre premier prototype ne plait pas aux clients testeurs. Quelle attitude adopter ?",
     "Ecouter leurs remarques et ameliorer le produit",
     ["Abandonner definitivement le projet", "Ignorer les avis et lancer la production",
      "Accuser les clients de ne rien comprendre"], FACILE, "Les retours negatifs sont une information precieuse."),
    ("Une cliente se plaint publiquement de votre service sur les reseaux sociaux. Que faites-vous ?",
     "Repondre poliment, proposer une solution et regler le probleme",
     ["Supprimer le commentaire et bloquer la cliente", "Repondre par une insulte", "Ignorer totalement le message"],
     FACILE, "Une reclamation bien traitee peut fideliser un client."),
    ("Votre boutique realise beaucoup de ventes mais vous manquez toujours d'argent. Que verifiez-vous en priorite ?",
     "Votre tresorerie et les delais de paiement de vos clients",
     ["La couleur de votre enseigne", "Le nombre d'abonnes sur les reseaux", "La marque de votre telephone"],
     MOYEN, "Un chiffre d'affaires eleve n'assure pas une tresorerie saine."),
    ("Un client vous demande un delai de paiement de 90 jours alors que vous payez vos fournisseurs comptant. Quel est le risque ?",
     "Un manque de tresorerie pour financer votre activite",
     ["Une hausse automatique de vos benefices", "Une reduction de vos impots",
      "Une amelioration immediate de votre image"], MOYEN, "Le decalage entre encaissements et decaissements cree un besoin de financement."),
    ("Vous vendez un produit a 1 500 FCFA alors qu'il vous coute 1 700 FCFA a produire. Que devez-vous faire ?",
     "Revoir vos couts ou augmenter votre prix",
     ["Vendre encore plus pour compenser", "Ne rien changer, le volume reglera tout",
      "Emprunter pour continuer a vendre a perte"], MOYEN, "Vendre a perte multiplie les pertes quand le volume augmente."),
    ("Trois concurrents proposent le meme produit que vous au meme prix. Quelle strategie privilegier ?",
     "Vous differencier par un service ou une qualite superieure",
     ["Copier exactement leur communication", "Baisser votre prix jusqu'a perdre de l'argent",
      "Attendre qu'ils ferment"], MOYEN, "La differenciation cree un avantage concurrentiel durable."),
    ("Vous avez une idee de service mais aucun budget. Quelle premiere etape est la plus raisonnable ?",
     "Tester l'idee a petite echelle avec les moyens disponibles",
     ["Emprunter 10 millions de FCFA immediatement", "Louer un immeuble entier",
      "Recruter dix salaries"], FACILE, "Le test a petite echelle limite le risque financier."),
    ("Un ami vous propose de s'associer sans rien ecrire. Que conseillez-vous ?",
     "Formaliser l'accord par ecrit avant de commencer",
     ["Commencer sans rien preciser", "Lui donner toute la gestion sans controle",
      "Refuser toute discussion sur l'argent"], FACILE, "Un accord ecrit previent les conflits futurs."),
    ("Votre activite marche bien et vous ne pouvez plus repondre a toutes les commandes. Que faites-vous ?",
     "Organiser votre production et deleguer certaines taches",
     ["Refuser toutes les nouvelles commandes definitivement", "Continuer seul quitte a livrer en retard",
      "Augmenter vos prix de 500 % immediatement"], MOYEN, "La croissance se gere par l'organisation et la delegation."),
    ("Un investisseur vous demande vos chiffres. Vous n'avez aucune comptabilite. Quelle consequence probable ?",
     "Il perdra confiance et hesitera a financer votre projet",
     ["Il investira davantage par curiosite", "Cela n'a aucune importance",
      "Il vous versera automatiquement une subvention"], MOYEN, "Des comptes clairs sont indispensables pour lever des fonds."),
    ("Vous constatez qu'un seul client represente 80 % de votre chiffre d'affaires. Quel est le principal risque ?",
     "Une forte dependance : sa perte mettrait l'entreprise en danger",
     ["Une hausse garantie de vos marges", "Une reduction de vos charges fixes",
      "Une meilleure protection contre la concurrence"], MOYEN, "La concentration du portefeuille client est un risque majeur."),
    ("Votre produit se vend bien a Douala. Vous voulez l'etendre a Garoua. Quelle precaution prendre ?",
     "Verifier que les besoins et habitudes locales sont comparables",
     ["Dupliquer l'offre sans aucune adaptation", "Baisser la qualite pour reduire les couts",
      "Changer completement de metier"], MOYEN, "Un marche qui fonctionne ailleurs doit etre reetudie localement."),
    ("Un fournisseur augmente ses prix de 30 %. Quelle reaction est la plus professionnelle ?",
     "Negocier, puis comparer avec d'autres fournisseurs",
     ["Arreter immediatement l'activite", "Accepter sans reflechir",
      "Insulter le fournisseur et rompre brutalement"], MOYEN, "La negociation et la mise en concurrence protegent la marge."),
    ("Vous lancez une nouvelle offre. Comment savoir rapidement si elle interesse le marche ?",
     "Proposer une version simple a un petit groupe de clients et mesurer leurs reactions",
     ["Attendre un an avant de demander un avis", "Se fier uniquement a l'avis de sa famille",
      "Lancer une campagne nationale couteuse d'emblee"], MOYEN, "Le test rapide reduit le risque et le cout de l'erreur."),
    ("Votre equipe est demotivee. Quelle action a le plus de chances d'aider ?",
     "Ecouter les difficultes et clarifier les objectifs de chacun",
     ["Menacer tout le monde de licenciement", "Ne rien dire et attendre",
      "Supprimer toutes les pauses"], FACILE, "L'ecoute et la clarte des objectifs nourrissent la motivation."),
    ("Vous devez choisir entre acheter une machine a credit ou louer une machine. Quel critere est central ?",
     "La capacite de votre tresorerie a supporter les echeances",
     ["La couleur de la machine", "L'avis de vos voisins", "La marque la plus connue au monde"],
     MOYEN, "Le choix depend de la capacite de remboursement et de l'usage prevu."),
    ("Vous vendez des jus naturels. Un client demande une facture. Que faites-vous ?",
     "Vous lui delivrez une facture conforme a votre activite",
     ["Vous refusez car c'est trop complique", "Vous inventez un montant different",
      "Vous lui demandez de revenir dans six mois"], FACILE, "La facture est une obligation et un gage de serieux."),
    ("Vous n'avez pas encore de clients mais depensez deja beaucoup en publicite. Quel conseil donner ?",
     "Valider d'abord l'interet reel du marche avant d'augmenter les depenses",
     ["Doubler le budget publicitaire", "Emprunter pour financer plus de publicite",
      "Arreter definitivement toute communication"], MOYEN, "La publicite amplifie une offre validee, elle ne la remplace pas."),
    ("Un concurrent baisse fortement ses prix. Quelle reaction est la plus prudente ?",
     "Analyser vos couts et renforcer ce qui vous differencie",
     ["Baisser vos prix sous votre cout de revient", "Fermer immediatement",
      "Copier son prix sans calculer"], MOYEN, "Une guerre des prix mal preparee detruit la rentabilite."),
    ("Vous voulez tester la demande pour un service de livraison. Quel indicateur suivre en priorite ?",
     "Le nombre de commandes reellement passees",
     ["Le nombre de likes sur une photo", "La couleur de votre moto",
      "Le nombre de reunions internes"], MOYEN, "Seules les commandes reelles prouvent la demande."),
    ("Votre stock de marchandises perissables se degrade avant la vente. Que faut-il ajuster ?",
     "La gestion des approvisionnements et la rotation des stocks",
     ["La couleur de l'emballage uniquement", "Le nom de l'entreprise",
      "Le nombre d'associes"], MOYEN, "Un stock mal dimensionne immobilise l'argent et se perd."),
    ("Un client regulier vous demande une remise importante. Quelle approche est la plus saine ?",
     "Verifier l'impact sur votre marge avant d'accepter",
     ["Accepter sans calculer", "Refuser sans discuter", "Doubler le prix pour compenser"],
     MOYEN, "Toute remise se decide en connaissant sa marge."),
    ("Votre entreprise grandit et vous melangez argent personnel et argent de l'activite. Quel risque ?",
     "Perdre la visibilite sur la rentabilite reelle de l'activite",
     ["Payer moins d'impots automatiquement", "Ameliorer votre comptabilite",
      "Faciliter l'obtention d'un credit"], MOYEN, "Separer les comptes est une regle de base de gestion."),
    ("Vous constatez que vos clients achetent surtout le week-end. Comment en tirer parti ?",
     "Adapter vos horaires, stocks et promotions a ces pics",
     ["Fermer le week-end", "Ignorer cette information",
      "Augmenter les prix uniquement en semaine sans raison"], MOYEN, "Les donnees de vente orientent les decisions operationnelles."),
    ("Vous n'avez pas de local mais vendez en ligne. Quel poste devient prioritaire ?",
     "La logistique et la fiabilite des livraisons",
     ["La decoration d'un bureau", "L'achat de mobilier de luxe", "La location d'un entrepot geant"],
     MOYEN, "En e-commerce, la livraison fait la reputation."),
    ("Deux associes ne s'entendent plus sur la strategie. Quelle demarche privilegier ?",
     "Revenir aux objectifs communs et arbitrer selon les statuts ou le pacte d'associes",
     ["Vider le compte bancaire de la societe", "Cesser de se parler",
      "Vendre le materiel en secret"], MOYEN, "Les documents fondateurs servent a trancher les desaccords."),
    ("Votre activite depend d'un seul fournisseur eloigne. Quelle mesure reduit le risque ?",
     "Identifier au moins un fournisseur alternatif",
     ["Commander toujours plus au meme fournisseur", "Arreter de commander",
      "Attendre une rupture pour reagir"], MOYEN, "La diversification des fournisseurs securise l'approvisionnement."),
    ("Vous voulez recruter votre premier employe. Quelle etape est indispensable ?",
     "Definir clairement le poste et les taches attendues",
     ["Recruter le premier venu sans description de poste", "Promettre un salaire sans le budgeter",
      "Recruter dix personnes d'un coup"], FACILE, "Une fiche de poste claire evite les malentendus."),
    ("Un client vous propose un gros marche mais exige un paiement dans six mois. Que verifiez-vous ?",
     "Votre capacite a financer la production en attendant le paiement",
     ["La couleur du logo du client", "Le nombre d'employes du client uniquement",
      "La meteo prevue dans six mois"], CHALLENGE, "Un gros contrat mal finance peut couler l'entreprise."),
    ("Vous constatez que vos couts fixes sont tres eleves et vos ventes irregulieres. Quelle piste explorer ?",
     "Transformer une partie des couts fixes en couts variables",
     ["Augmenter encore les couts fixes", "Supprimer toute activite commerciale",
      "Ignorer la structure de couts"], CHALLENGE, "Des couts variables amortissent mieux les variations d'activite."),
    ("Vous vendez un service premium mais communiquez comme un discounter. Quel probleme cela pose-t-il ?",
     "Une incoherence entre le positionnement et la communication",
     ["Une hausse automatique des marges", "Une meilleure fidelisation",
      "Une reduction des couts de production"], CHALLENGE, "Le positionnement doit etre coherent sur toute l'offre."),
    ("Vous avez teste votre offre : peu de clients reviennent. Que faut-il analyser d'abord ?",
     "Les raisons de non-retour : qualite, prix, experience ou besoin mal couvert",
     ["Le nombre de publications sur les reseaux", "La taille de votre local",
      "Le nombre d'associes"], MOYEN, "Le taux de retour mesure la valeur reelle percue."),
    ("Une opportunite de marche apparait mais vous manquez de competences techniques. Quelle option est la plus realiste ?",
     "Vous associer ou recruter la competence manquante",
     ["Pretendre maitriser le sujet", "Renoncer a toute croissance",
      "Attendre plusieurs annees sans rien faire"], MOYEN, "Completer l'equipe est souvent plus rapide que tout apprendre seul."),
    ("Vous devez fixer le prix d'un nouveau produit. Quelle base est la plus solide ?",
     "Le cout de revient, le prix du marche et la valeur percue par le client",
     ["Uniquement l'avis de votre cousin", "Le prix le plus bas possible",
      "Un chiffre choisi au hasard"], MOYEN, "Le prix combine couts, concurrence et valeur percue."),
    ("Votre entreprise informelle grandit. Quel avantage y a-t-il a se formaliser ?",
     "Acceder au credit, aux marches publics et a des clients plus exigeants",
     ["Payer plus cher sans aucune contrepartie", "Perdre tous ses clients",
      "Etre oblige de fermer"], MOYEN, "La formalisation ouvre des portes commerciales et financieres."),
    ("Vous voulez convaincre une banque de financer votre projet. Quel document est central ?",
     "Un business plan avec des previsions financieres realistes",
     ["Une photo de votre boutique", "Une lettre de recommandation d'un ami",
      "Une liste de vos souhaits personnels"], FACILE, "Le business plan structure la demande de financement."),
    ("Votre marge est correcte mais vos frais de transport explosent. Quelle action prioritaire ?",
     "Optimiser les tournees et regrouper les livraisons",
     ["Augmenter les prix de 200 %", "Supprimer la livraison sans prevenir",
      "Ignorer ce poste de cout"], MOYEN, "L'optimisation logistique protege directement la marge."),
    ("Un client vous demande un produit que vous ne proposez pas mais que d'autres reclament aussi. Que faire ?",
     "Etudier la faisabilite d'ajouter ce produit a votre offre",
     ["Refuser sans y reflechir", "Changer completement de metier immediatement",
      "Envoyer tous vos clients chez un concurrent"], FACILE, "Les demandes repetees signalent une opportunite."),
    ("Vous constatez des vols recurrents dans votre stock. Quelle mesure est la plus structurante ?",
     "Mettre en place un inventaire regulier et un controle des entrees-sorties",
     ["Accuser tout le monde sans preuve", "Fermer la boutique definitivement",
      "Ne plus tenir de stock du tout"], MOYEN, "Le controle des stocks limite les pertes."),
    ("Vous demarrez seul et devez tout faire. Quel principe de gestion du temps appliquer ?",
     "Prioriser les taches qui apportent des clients et du chiffre d'affaires",
     ["Commencer par les taches les plus agreables", "Faire toutes les taches en meme temps",
      "Reporter systematiquement les taches importantes"], FACILE, "La priorisation cree de l'impact avec des moyens limites."),
    ("Un partenaire vous propose un contrat verbal tres avantageux. Quelle precaution prendre ?",
     "Exiger un contrat ecrit precisant les engagements de chacun",
     ["Accepter immediatement sans ecrit", "Refuser tout partenariat par principe",
      "Signer sans lire"], FACILE, "L'ecrit protege les deux parties."),
    ("Vous vendez un produit saisonnier. Comment lisser vos revenus sur l'annee ?",
     "Developper une offre complementaire en dehors de la saison",
     ["Fermer six mois par an sans rien preparer", "Stocker sans limite toute l'annee",
      "Augmenter les prix hors saison sans justification"], CHALLENGE, "La diversification saisonniere stabilise la tresorerie."),
    ("Votre application compte beaucoup d'inscrits mais peu d'utilisateurs actifs. Que revele cet indicateur ?",
     "Que la valeur d'usage reelle du service reste faible",
     ["Que le produit est deja rentable", "Que le marche est sature",
      "Que la publicite est inutile"], CHALLENGE, "L'activite reelle compte plus que le nombre d'inscriptions."),
    ("Vous devez presenter votre projet en une minute a un investisseur. Que mettez-vous en avant ?",
     "Le probleme resolu, la solution, le marche et votre traction",
     ["L'histoire complete de votre famille", "Le detail technique de chaque ligne de code",
      "La liste de vos loisirs"], MOYEN, "Un bon pitch va a l'essentiel : probleme, solution, marche, preuve."),
    ("Vous constatez que 20 % de vos produits font 80 % de vos ventes. Comment exploiter ce constat ?",
     "Concentrer vos efforts et vos stocks sur ces produits porteurs",
     ["Supprimer les produits qui marchent", "Ignorer completement l'information",
      "Multiplier les references sans analyse"], CHALLENGE, "C'est une application du principe de Pareto."),
    ("Un jeune veut se lancer mais craint l'echec. Quel conseil est le plus utile ?",
     "Commencer petit, tester, apprendre et ajuster progressivement",
     ["Investir toutes ses economies d'un coup", "Ne jamais essayer",
      "Copier exactement un projet sans le comprendre"], FACILE, "L'approche progressive limite le cout de l'erreur."),
    ("Votre produit est bon mais personne ne le connait. Quel est le probleme principal ?",
     "Un manque de visibilite et de communication ciblee",
     ["Un exces de qualite", "Un prix trop bas uniquement",
      "Un nombre d'associes insuffisant"], FACILE, "Un bon produit invisible ne se vend pas."),
    ("Vous recevez une commande superieure a votre capacite de production. Que faites-vous ?",
     "Negocier des delais realistes ou sous-traiter une partie",
     ["Accepter et livrer n'importe quoi", "Refuser sans explication",
      "Promettre puis disparaitre"], MOYEN, "Mieux vaut un delai negocie qu'une promesse non tenue."),
]


def build() -> list[Q]:
    return [
        Q(question, correct, wrong, diff, "entrepreneuriat,mise-en-situation", expl)
        for question, correct, wrong, diff, expl in SCENARIOS
    ]
