# -*- coding: utf-8 -*-
"""Banque Entrepreneuriat : mises en situation (suite) et posture entrepreneuriale."""

from __future__ import annotations

from .common import CHALLENGE, FACILE, MOYEN, Q

SCENARIOS = [
    ("Vous tenez une petite restauration. Les clients se plaignent de l'attente. Quelle action prioritaire ?",
     "Reorganiser la preparation pour reduire le temps de service",
     ["Augmenter les prix", "Reduire les portions", "Fermer plus tot"], FACILE,
     "L'experience client depend directement du temps d'attente."),
    ("Votre marchandise reste invendue depuis trois mois. Que faites-vous ?",
     "Analyser pourquoi elle ne se vend pas puis ajuster prix, presentation ou cible",
     ["Commander la meme chose en plus grande quantite", "Ignorer le stock",
      "Jeter la marchandise sans reflexion"], MOYEN, "Un stock dormant immobilise de la tresorerie."),
    ("Un client vous demande un produit moins cher que votre gamme. Quelle reponse est la plus commerciale ?",
     "Lui proposer une alternative adaptee a son budget dans votre offre",
     ["Lui dire qu'il n'a pas les moyens", "Lui vendre a perte",
      "L'envoyer chez un concurrent sans rien proposer"], MOYEN, "Une gamme d'entree retient le client."),
    ("Vous recevez une commande importante d'un client inconnu. Quelle precaution prendre ?",
     "Demander un acompte avant de lancer la production",
     ["Tout produire sans garantie", "Livrer et esperer etre paye",
      "Refuser toute commande importante"], MOYEN, "L'acompte securise la tresorerie et engage le client."),
    ("Vous constatez que votre principal concurrent recrute vos meilleurs employes. Que faire ?",
     "Comprendre pourquoi ils partent et ameliorer conditions et perspectives",
     ["Interdire aux employes de parler entre eux", "Baisser tous les salaires",
      "Ne rien changer"], MOYEN, "La retention passe par l'ecoute et la reconnaissance."),
    ("Votre entreprise vend bien mais vous travaillez 15 heures par jour sans progresser. Quel diagnostic ?",
     "Votre modele repose trop sur vous : il faut organiser et deleguer",
     ["Il faut travailler 20 heures par jour", "Il faut arreter de vendre",
      "Il faut licencier tout le monde"], MOYEN, "Un modele non delegable ne passe pas a l'echelle."),
    ("Un fournisseur livre systematiquement en retard. Quelle demarche structurer ?",
     "Formaliser les delais dans le contrat et prevoir un fournisseur de secours",
     ["Attendre indefiniment", "Payer plus cher sans rien exiger",
      "Arreter de vendre le produit concerne"], MOYEN, "Le contrat et l'alternative reduisent le risque."),
    ("Vous avez trois idees de projet et peu de temps. Comment choisir ?",
     "Tester rapidement celle qui repond au besoin le plus urgent et le plus verifiable",
     ["Lancer les trois en meme temps", "Choisir au hasard",
      "Attendre un an avant de decider"], MOYEN, "La priorisation par la validation du besoin evite la dispersion."),
    ("Votre projet exige un capital de 5 millions FCFA que vous n'avez pas. Quelle approche progressive ?",
     "Reduire le perimetre pour demarrer avec un investissement plus faible",
     ["Abandonner definitivement", "Emprunter sans plan de remboursement",
      "Attendre de gagner a la loterie"], MOYEN, "Reduire le perimetre permet de demarrer et de prouver le concept."),
    ("Une association vous propose un partenariat sans contrepartie claire. Que verifiez-vous ?",
     "Ce que chacun apporte et ce que chacun attend, par ecrit",
     ["Rien, l'intention suffit", "Uniquement la reputation",
      "Uniquement le nombre de membres"], MOYEN, "Un partenariat se definit par des engagements reciproques."),
    ("Vos ventes chutent brutalement ce mois-ci. Quelle est la premiere chose a faire ?",
     "Identifier la cause : saisonnalite, concurrence, qualite ou prix",
     ["Licencier immediatement", "Doubler les prix", "Fermer l'entreprise"], FACILE,
     "Le diagnostic precede l'action corrective."),
    ("Un employe propose une idee d'amelioration. Quelle attitude adopter ?",
     "L'ecouter, l'evaluer et la tester si elle est pertinente",
     ["La rejeter par principe", "La copier sans le citer", "Le sanctionner"],
     FACILE, "L'intelligence collective ameliore l'entreprise."),
    ("Votre produit plait mais coute trop cher a produire. Quelle piste explorer d'abord ?",
     "Revoir la conception et les achats pour reduire le cout sans degrader la valeur",
     ["Baisser la qualite sans prevenir", "Arreter la production",
      "Augmenter le prix de 300 %"], MOYEN, "L'optimisation des couts precede la hausse de prix."),
    ("Vous devez choisir entre deux emplacements : un tres frequente et cher, un calme et bon marche. Quel critere decide ?",
     "La nature de votre activite et le comportement de vos clients",
     ["Uniquement le loyer", "Uniquement la beaute du batiment",
      "L'avis d'un inconnu"], MOYEN, "L'emplacement se choisit en fonction du flux client necessaire."),
    ("Vous vendez un service B2B. Le decideur n'est pas la personne que vous rencontrez. Que faire ?",
     "Identifier le vrai decideur et adapter votre argumentaire",
     ["Insister aupres de la mauvaise personne", "Abandonner la vente",
      "Envoyer une facture directement"], CHALLENGE, "Identifier le circuit de decision est cle en B2B."),
    ("Un client conteste une facture. Quelle demarche professionnelle ?",
     "Verifier le contrat et les prestations livrees, puis clarifier calmement",
     ["Menacer immediatement", "Annuler la facture sans verifier",
      "Ignorer la contestation"], MOYEN, "La verification factuelle desamorce le conflit."),
    ("Vous voulez vendre a l'international. Quelle premiere verification est essentielle ?",
     "Les exigences reglementaires et logistiques du pays cible",
     ["La couleur preferee des habitants", "Le nombre d'aeroports du pays",
      "Le classement sportif du pays"], MOYEN, "Normes, douanes et logistique conditionnent l'export."),
    ("Vous constatez que vos concurrents communiquent beaucoup sur les reseaux et vous pas du tout. Que faire ?",
     "Choisir un ou deux canaux adaptes a votre cible et publier regulierement",
     ["Ouvrir dix comptes et n'en animer aucun", "Ne rien faire",
      "Payer pour de faux abonnes"], MOYEN, "Mieux vaut un canal bien tenu que dix abandonnes."),
    ("Votre activite depend d'une seule competence que vous detenez seul. Quel risque ?",
     "L'activite s'arrete si vous etes indisponible",
     ["Une croissance automatique", "Une meilleure rentabilite",
      "Une protection contre les concurrents"], MOYEN, "La dependance a une personne est un risque operationnel."),
    ("Vous avez peu de moyens pour tester une idee de service. Quelle methode est adaptee ?",
     "Proposer le service manuellement a quelques clients avant d'automatiser",
     ["Developper une plateforme complete d'abord", "Recruter vingt personnes",
      "Louer un immeuble"], MOYEN, "Le test manuel valide la demande avant l'investissement technique."),
    ("Vous hesitez entre baisser le prix ou ajouter un service. Quel raisonnement privilegier ?",
     "Comparer l'effet sur la marge et sur la valeur percue par le client",
     ["Choisir au hasard", "Toujours baisser le prix",
      "Toujours augmenter le prix"], MOYEN, "La decision se prend sur la marge et la perception client."),
    ("Un investisseur vous demande une part majoritaire des le premier tour. Que devez-vous considerer ?",
     "La perte de controle sur les decisions strategiques",
     ["Uniquement le montant propose", "Rien, il faut accepter",
      "Le nom de son entreprise"], CHALLENGE, "Ceder la majorite tot limite la marge de manoeuvre du fondateur."),
    ("Votre production depend de l'electricite et les coupures sont frequentes. Quelle solution structurante ?",
     "Prevoir une source d'energie de secours et planifier la production",
     ["Ignorer le probleme", "Arreter l'activite",
      "Attendre que le reseau s'ameliore seul"], MOYEN, "La continuite d'activite se prepare."),
    ("Vous constatez que vos clients reviennent surtout grace au bouche-a-oreille. Comment l'amplifier ?",
     "Encourager le parrainage et soigner la qualite de service",
     ["Interdire aux clients d'en parler", "Supprimer le service apres-vente",
      "Augmenter les prix sans prevenir"], MOYEN, "Le parrainage structure le bouche-a-oreille."),
    ("Vous devez presenter vos comptes a un partenaire. Vos donnees sont eparpillees. Quelle bonne pratique ?",
     "Tenir une comptabilite reguliere et centralisee des le depart",
     ["Reconstituer les chiffres de memoire", "Refuser de communiquer",
      "Inventer des chiffres"], FACILE, "La regularite comptable evite les reconstitutions hasardeuses."),
    ("Vous voulez recruter mais ne pouvez pas payer un salaire plein. Quelle option est realiste ?",
     "Commencer par un temps partiel, un stage encadre ou une prestation ponctuelle",
     ["Promettre un salaire que vous ne pourrez pas payer", "Recruter dix personnes",
      "Renoncer definitivement a toute aide"], MOYEN, "Adapter le format de collaboration a la capacite financiere."),
    ("Une opportunite tres rentable vous eloigne totalement de votre metier. Quel risque ?",
     "Disperser vos ressources et affaiblir votre activite principale",
     ["Doubler automatiquement vos benefices", "Reduire vos charges fixes",
      "Ameliorer votre image de marque"], CHALLENGE, "La dispersion est un risque classique de croissance."),
    ("Vos couts augmentent mais vos clients sont sensibles au prix. Quelle option explorer en premier ?",
     "Reduire les couts internes et ameliorer la valeur avant d'augmenter le prix",
     ["Augmenter le prix de 100 % immediatement", "Vendre a perte durablement",
      "Ne rien faire et attendre"], MOYEN, "L'ajustement des couts precede la hausse de prix."),
    ("Vous voulez savoir si votre prix est accepte par le marche. Quel test simple ?",
     "Proposer le prix a un petit groupe de clients reels et observer les achats",
     ["Demander a votre famille uniquement", "Consulter un horoscope",
      "Choisir un prix au hasard"], MOYEN, "Seul un test avec de vrais acheteurs valide un prix."),
    ("Votre equipe ne comprend pas la direction du projet. Quelle est votre responsabilite ?",
     "Clarifier la vision, les priorites et le role de chacun",
     ["Attendre qu'ils devinent", "Changer de projet chaque semaine",
      "Communiquer uniquement par ecrit anonyme"], FACILE, "La clarte est une responsabilite du dirigeant."),
    ("Un concurrent lance une innovation qui rend votre offre moins attractive. Que faites-vous ?",
     "Analyser l'innovation et adapter votre offre ou votre positionnement",
     ["Nier le changement", "Attaquer publiquement le concurrent",
      "Fermer immediatement"], MOYEN, "L'adaptation est plus efficace que le deni."),
    ("Vos charges fixes representent 70 % de vos couts et vos ventes varient beaucoup. Quel danger ?",
     "Une perte rapide des que les ventes baissent",
     ["Une rentabilite garantie", "Une baisse automatique des impots",
      "Une hausse mecanique de la marge"], CHALLENGE, "Des charges fixes elevees rendent l'entreprise fragile."),
    ("Vous devez arbitrer entre livrer vite ou livrer parfaitement. Quel principe suivre ?",
     "Livrer une qualite conforme a la promesse faite au client",
     ["Toujours livrer en retard", "Toujours sacrifier la qualite",
      "Ne jamais livrer"], MOYEN, "La promesse client fixe le niveau attendu."),
    ("Un client important demande une exclusivite territoriale. Quelle precaution ?",
     "Encadrer la duree, le volume minimal et les conditions de sortie",
     ["Accepter sans limite de duree", "Refuser sans discuter",
      "Signer sans lire"], CHALLENGE, "Une exclusivite mal cadree bloque le developpement."),
    ("Vous constatez que votre marge est bonne mais votre volume faible. Quelle piste ?",
     "Travailler la visibilite et la conquete de nouveaux clients",
     ["Baisser la qualite", "Augmenter les charges fixes",
      "Reduire encore le volume"], MOYEN, "Bonne marge et faible volume appellent un effort commercial."),
    ("Vous constatez l'inverse : gros volume mais marge tres faible. Quelle piste ?",
     "Revoir les couts, les prix ou la composition de la gamme",
     ["Vendre encore plus a perte", "Ne rien changer",
      "Supprimer tous les clients"], MOYEN, "Le volume ne compense pas une marge insuffisante."),
    ("Vous demarrez une activite de couture a domicile. Quel premier investissement est prioritaire ?",
     "Le materiel qui permet de produire et de livrer les premieres commandes",
     ["Une enseigne lumineuse geante", "Un site web tres couteux",
      "Un vehicule de fonction"], FACILE, "On investit d'abord dans ce qui genere du chiffre d'affaires."),
    ("Vous vendez des produits frais et devez limiter les pertes. Quelle pratique adopter ?",
     "Commander selon les ventes reelles et suivre la rotation des stocks",
     ["Commander toujours le maximum", "Ne jamais commander",
      "Stocker sans controler les dates"], MOYEN, "La rotation des stocks conditionne la rentabilite du frais."),
    ("Un client vous demande une prestation que vous ne maitrisez pas. Quelle reponse est la plus professionnelle ?",
     "Etre honnete et proposer un partenaire competent ou un delai d'apprentissage realiste",
     ["Accepter et improviser", "Promettre puis disparaitre",
      "Facturer sans livrer"], FACILE, "L'honnetete preserve la relation et la reputation."),
    ("Votre chiffre d'affaires progresse mais votre benefice diminue. Que verifiez-vous ?",
     "L'evolution de vos couts et de votre structure de marge",
     ["Le nombre de likes", "La couleur de vos emballages",
      "Le nombre de reunions"], CHALLENGE, "Une croissance non maitrisee peut detruire la marge."),
]

POSTURE = [
    ("Quelle qualite est la plus utile a un entrepreneur face a l'incertitude ?", "La capacite d'adaptation",
     ["L'entetement absolu", "L'indifference aux clients", "La peur de decider"], FACILE,
     "S'adapter permet de survivre aux imprevus."),
    ("Que faire d'un echec entrepreneurial ?", "En tirer des enseignements pour le projet suivant",
     ["Le cacher et l'oublier", "Accuser uniquement les autres", "Renoncer definitivement"],
     FACILE, "L'echec est une source d'apprentissage."),
    ("Quelle attitude distingue un entrepreneur d'un simple executant ?", "La prise d'initiative et de responsabilite",
     ["L'attente des instructions", "Le refus de decider", "La fuite des responsabilites"],
     FACILE, "L'entrepreneur assume ses choix."),
    ("Pourquoi un entrepreneur doit-il savoir dire non ?", "Pour proteger ses ressources et rester concentre sur l'essentiel",
     ["Pour vexer ses clients", "Pour eviter de travailler", "Pour reduire son chiffre d'affaires"],
     MOYEN, "Dire non protege la strategie et le temps."),
    ("Quel est l'interet de s'entourer d'un mentor ?", "Beneficier d'une experience et d'un regard exterieur",
     ["Deleguer toutes ses decisions", "Eviter de travailler", "Obtenir un financement automatique"],
     FACILE, "Le mentor accelere l'apprentissage."),
    ("Que signifie prendre un risque calcule ?", "Accepter une incertitude apres avoir evalue les consequences possibles",
     ["Agir sans reflechir", "Ne jamais rien tenter", "Miser toutes ses ressources au hasard"],
     MOYEN, "Le risque calcule s'appuie sur une evaluation."),
    ("Pourquoi la perseverance est-elle importante en entrepreneuriat ?",
     "Parce que les resultats arrivent rarement des les premiers essais",
     ["Parce qu'il ne faut jamais changer d'avis", "Parce que les clients aiment attendre",
      "Parce que la loi l'exige"], FACILE, "Perseverer n'est pas s'obstiner sans apprendre."),
    ("Quelle difference entre perseverance et obstination ?",
     "La perseverance s'appuie sur l'apprentissage, l'obstination ignore les signaux",
     ["Il n'y a aucune difference", "L'obstination est toujours meilleure",
      "La perseverance signifie abandonner"], CHALLENGE, "Perseverer suppose d'ajuster sa methode."),
    ("Pourquoi un entrepreneur doit-il continuer a se former ?", "Parce que les marches et les outils evoluent en permanence",
     ["Pour obtenir des diplomes decoratifs", "Pour eviter de travailler",
      "Parce que la loi l'impose"], FACILE, "La formation continue maintient la competitivite."),
    ("Quel est l'interet de faire partie d'un reseau d'entrepreneurs ?",
     "Echanger des informations, des opportunites et des solutions",
     ["Copier les autres sans reflechir", "Eviter la concurrence par la loi",
      "Obtenir des clients garantis"], FACILE, "Le reseau est une source d'opportunites et d'entraide."),
    ("Que designe l'esprit d'entreprise ?", "La volonte de creer, d'innover et de prendre des initiatives",
     ["Le refus du changement", "La recherche de la securite absolue",
      "L'attente d'un emploi public"], FACILE, "L'esprit d'entreprise combine initiative et prise de risque."),
    ("Quel comportement nuit le plus a la credibilite d'un entrepreneur ?",
     "Promettre des delais ou des resultats qu'il ne peut pas tenir",
     ["Communiquer regulierement", "Reconnaitre une erreur", "Demander conseil"],
     MOYEN, "Les promesses non tenues detruisent la confiance."),
    ("Pourquoi la ponctualite compte-t-elle en affaires ?", "Parce qu'elle traduit le respect et la fiabilite",
     ["Parce qu'elle augmente les prix", "Parce qu'elle remplace la qualite",
      "Parce qu'elle evite de payer les taxes"], FACILE, "La fiabilite se construit sur des details."),
    ("Quel est le role de la vision dans un projet entrepreneurial ?", "Donner une direction claire aux decisions et a l'equipe",
     ["Remplacer la comptabilite", "Fixer les impots", "Choisir les couleurs du logo"],
     MOYEN, "La vision aligne les efforts."),
    ("Pourquoi ecouter davantage que parler lors d'un entretien client ?",
     "Parce que le client revele ses besoins reels quand on le laisse s'exprimer",
     ["Parce que parler est interdit", "Parce que le silence fait vendre seul",
      "Parce que les clients n'aiment pas les questions"], MOYEN, "L'ecoute active revele les besoins."),
    ("Quelle erreur frequente commettent les debutants avec leur idee ?",
     "La garder secrete et ne jamais la confronter au marche",
     ["La tester trop souvent", "Ecouter trop de clients",
      "Demander trop d'avis a des experts"], MOYEN, "Une idee non confrontee au marche reste une hypothese."),
    ("Que vaut une idee sans execution ?", "Peu de chose : c'est l'execution qui cree la valeur",
     ["Elle vaut toujours des millions", "Elle se vend automatiquement",
      "Elle rapporte sans travail"], MOYEN, "L'execution transforme l'idee en entreprise."),
    ("Pourquoi definir des objectifs ecrits ?", "Pour mesurer les progres et rester responsable de ses engagements",
     ["Pour remplir des dossiers", "Pour impressionner la famille",
      "Pour eviter de decider"], FACILE, "Ce qui se mesure se pilote."),
    ("Comment un entrepreneur peut-il gerer le stress lie a l'incertitude ?",
     "En planifiant, en s'entourant et en decoupant les problemes en etapes",
     ["En ignorant tous les problemes", "En travaillant sans jamais se reposer",
      "En prenant toutes les decisions seul et vite"], MOYEN, "Structurer et partager reduit la charge mentale."),
    ("Quelle est la valeur d'un premier client satisfait ?", "Il devient une reference et une source de recommandations",
     ["Aucune, seul le volume compte", "Il fait baisser les prix",
      "Il empeche d'en trouver d'autres"], FACILE, "Les premieres references facilitent les ventes suivantes."),
]


def build() -> list[Q]:
    qs = [Q(q, c, w, d, "entrepreneuriat,mise-en-situation", e) for q, c, w, d, e in SCENARIOS]
    qs += [Q(q, c, w, d, "entrepreneuriat,posture", e) for q, c, w, d, e in POSTURE]
    return qs
