# -*- coding: utf-8 -*-
"""Banque Innovation & IA : culture generale du numerique et des inventions."""

from __future__ import annotations

from .common import CHALLENGE, FACILE, MOYEN, Q, others

# inventeur/pionnier -> (realisation, domaine, difficulte)
PIONNIERS = {
    "Tim Berners-Lee": ("le World Wide Web", "Internet", MOYEN),
    "Alan Turing": ("le test de Turing et les bases de l'informatique moderne", "L'informatique", MOYEN),
    "Ada Lovelace": ("le premier algorithme destine a une machine", "La programmation", MOYEN),
    "Grace Hopper": ("les premiers travaux sur les compilateurs", "La programmation", CHALLENGE),
    "John McCarthy": ("l'expression intelligence artificielle", "L'intelligence artificielle", CHALLENGE),
    "Joseph Weizenbaum": ("ELIZA, l'un des premiers agents conversationnels", "L'intelligence artificielle", CHALLENGE),
    "Geoffrey Hinton": ("les avancees majeures de l'apprentissage profond", "L'intelligence artificielle", CHALLENGE),
    "Yann LeCun": ("les reseaux de neurones convolutifs pour l'image", "L'intelligence artificielle", CHALLENGE),
    "Ray Tomlinson": ("l'usage du symbole arobase dans les adresses e-mail", "Internet", CHALLENGE),
    "Vint Cerf": ("les protocoles de communication d'internet", "Internet", CHALLENGE),
    "Martin Cooper": ("le premier appel depuis un telephone mobile", "Les telecommunications", CHALLENGE),
    "Alexander Graham Bell": ("le telephone", "Les telecommunications", FACILE),
    "Guglielmo Marconi": ("la telegraphie sans fil", "Les telecommunications", MOYEN),
    "Johannes Gutenberg": ("l'imprimerie a caracteres mobiles en Europe", "L'imprimerie", MOYEN),
    "Thomas Edison": ("l'ampoule electrique commercialisable", "L'energie", FACILE),
    "Karl Benz": ("la premiere automobile a moteur a essence", "Les transports", MOYEN),
    "Les freres Wright": ("le premier vol motorise controle", "Les transports", MOYEN),
    "Louis Pasteur": ("la vaccination moderne et la pasteurisation", "La sante", FACILE),
    "Alexander Fleming": ("la penicilline", "La sante", MOYEN),
    "Jack Kilby": ("le circuit integre", "L'electronique", CHALLENGE),
    "Steve Wozniak": ("les premiers ordinateurs Apple", "L'informatique", MOYEN),
    "Larry Page": ("l'algorithme de classement a l'origine de Google", "Internet", MOYEN),
    "Arthur Zang": ("le Cardiopad, tablette d'examen cardiaque", "La sante", MOYEN),
    "Verone Mankou": ("la premiere tablette concue en Afrique centrale", "L'electronique", CHALLENGE),
}

DATES = [
    ("En quelle annee l'expression intelligence artificielle a-t-elle ete officiellement proposee ?", "1956",
     ["1912", "1985", "2010"], CHALLENGE, "Lors de la conference de Dartmouth en 1956."),
    ("Quel ordinateur a battu le champion du monde d'echecs Garry Kasparov en 1997 ?", "Deep Blue",
     ["Watson", "AlphaGo", "ENIAC"], MOYEN, "Deep Blue, developpe par IBM, l'emporte en 1997."),
    ("Quel programme a battu un champion du monde de jeu de go en 2016 ?", "AlphaGo",
     ["Deep Blue", "ELIZA", "Siri"], MOYEN, "AlphaGo a battu Lee Sedol en 2016."),
    ("En quelle annee le World Wide Web a-t-il ete invente ?", "1989",
     ["1969", "1999", "2005"], MOYEN, "Tim Berners-Lee formule sa proposition en 1989 au CERN."),
    ("Quel evenement a marque l'annee 2007 dans la telephonie mobile ?", "Le lancement du premier iPhone",
     ["L'invention du telephone", "La creation d'internet", "Le lancement de la 5G"],
     MOYEN, "Le premier iPhone est presente en 2007."),
    ("Quelle technologie a rendu les assistants conversationnels grand public tres populaires a partir de 2022 ?",
     "Les grands modeles de langage", ["Le fax", "Le minitel", "La disquette"],
     MOYEN, "Les modeles de langage generatifs ont democratise l'IA conversationnelle."),
    ("Qu'est-ce que le premier reseau ancetre d'internet ?", "ARPANET",
     ["Le minitel", "Le telex", "Le cable transatlantique"], CHALLENGE, "ARPANET est ne a la fin des annees 1960."),
    ("Quelle machine est consideree comme l'un des premiers ordinateurs electroniques ?", "L'ENIAC",
     ["Le Macintosh", "Le Commodore 64", "Le Raspberry Pi"], CHALLENGE, "L'ENIAC date des annees 1940."),
    ("Quelle loi affirme que le nombre de transistors sur une puce double environ tous les deux ans ?", "La loi de Moore",
     ["La loi de Pareto", "La loi de l'offre", "La loi de Murphy"], CHALLENGE, "Formulee par Gordon Moore."),
    ("Quel support a precede la cle USB pour transporter des fichiers ?", "La disquette",
     ["Le disque dur externe SSD", "La carte SIM", "Le code QR"], MOYEN, "La disquette a domine jusqu'aux annees 1990."),
]

CULTURE = [
    ("Une intelligence artificielle comprend-elle vraiment le sens de ce qu'elle ecrit ?",
     "Non, elle produit des reponses probables a partir de donnees d'entrainement",
     ["Oui, exactement comme un humain", "Oui, elle a des emotions",
      "Oui, elle possede une conscience"], MOYEN, "L'IA calcule des probabilites, elle ne comprend pas comme un humain."),
    ("Une IA peut-elle se tromper ?", "Oui, elle peut produire des reponses fausses avec assurance",
     ["Non, elle est infaillible", "Non, elle verifie toujours ses sources",
      "Non, elle refuse de repondre en cas de doute"], FACILE, "Les erreurs d'IA sont frequentes : il faut verifier."),
    ("Quelle precaution prendre avec une reponse fournie par une IA ?", "Verifier les informations importantes avant de les utiliser",
     ["Les publier telles quelles", "Les considerer comme des faits certains",
      "Les transmettre sans lecture"], FACILE, "La verification humaine reste indispensable."),
    ("D'ou vient la connaissance d'une intelligence artificielle generative ?",
     "Des tres grandes quantites de donnees sur lesquelles elle a ete entrainee",
     ["De sa propre experience de la vie", "De ses conversations avec ses amis",
      "De ses reves"], MOYEN, "L'IA apprend a partir de donnees, pas d'experience vecue."),
    ("Pourquoi dit-on que la qualite des donnees determine la qualite d'une IA ?",
     "Parce qu'un modele entraine sur des donnees biaisees ou fausses produira des resultats biaises ou faux",
     ["Parce que les donnees coutent cher", "Parce que les donnees sont toujours parfaites",
      "Parce que l'IA choisit ses donnees seule"], MOYEN, "Des donnees de mauvaise qualite donnent de mauvais resultats."),
    ("L'intelligence artificielle va-t-elle supprimer tous les emplois ?",
     "Non, elle transforme les metiers : certaines taches disparaissent, d'autres apparaissent",
     ["Oui, tous les emplois vont disparaitre", "Non, elle n'aura aucun effet sur le travail",
      "Oui, sauf les emplois agricoles"], MOYEN, "L'IA modifie la repartition des taches plus qu'elle ne supprime tout."),
    ("Quel usage de l'IA est le plus realiste pour une petite entreprise camerounaise aujourd'hui ?",
     "Gagner du temps sur la redaction, la traduction et le service client",
     ["Remplacer tout le personnel", "Construire un satellite",
      "Se passer totalement de comptabilite"], FACILE, "L'IA est d'abord un gain de productivite sur des taches simples."),
    ("Quelle est la difference entre automatiser et innover ?",
     "Automatiser reproduit une tache plus vite, innover cree une facon nouvelle de repondre a un besoin",
     ["Il n'y a aucune difference", "Innover signifie acheter des machines",
      "Automatiser signifie recruter"], MOYEN, "L'automatisation est un moyen, l'innovation un changement de valeur."),
    ("L'innovation exige-t-elle toujours une technologie de pointe ?",
     "Non, une nouvelle organisation ou un nouvel usage peut suffire",
     ["Oui, sans technologie il n'y a pas d'innovation", "Oui, il faut toujours un brevet",
      "Oui, il faut obligatoirement un laboratoire"], MOYEN, "L'innovation d'usage ou d'organisation compte autant."),
    ("Qu'est-ce que l'innovation frugale ?", "Obtenir un resultat utile avec des ressources tres limitees",
     ["Depenser beaucoup pour innover", "Copier une technologie etrangere",
      "Refuser toute nouveaute"], MOYEN, "L'innovation frugale est particulierement adaptee aux contextes contraints."),
    ("Pourquoi le telephone mobile est-il un levier d'innovation majeur en Afrique ?",
     "Parce qu'il est tres repandu et permet d'acceder aux services sans infrastructure lourde",
     ["Parce qu'il est rare", "Parce qu'il remplace l'electricite",
      "Parce qu'il est interdit ailleurs"], FACILE, "Le mobile sert de porte d'entree aux services numeriques."),
    ("Qu'appelle-t-on le saut technologique en Afrique ?",
     "Le fait d'adopter directement une technologie recente sans passer par les etapes intermediaires",
     ["Le refus des technologies", "L'obligation d'utiliser d'anciennes machines",
      "L'interdiction d'importer"], CHALLENGE, "Exemple : passer du cash au mobile money sans generaliser le cheque."),
    ("Quel est le principal avantage du cloud pour une petite structure ?",
     "Acceder a des outils puissants sans acheter de serveurs",
     ["Supprimer le besoin d'internet", "Garantir des ventes",
      "Eviter toute sauvegarde"], MOYEN, "Le cloud mutualise l'infrastructure."),
    ("Quel est le principal inconvenient d'une dependance totale a internet ?",
     "L'activite s'arrete en cas de coupure de connexion",
     ["Les couts deviennent nuls", "La securite devient parfaite",
      "Les clients disparaissent"], MOYEN, "Il faut prevoir un mode degrade."),
    ("Que designe un usage responsable de l'intelligence artificielle ?",
     "Utiliser l'IA en verifiant ses resultats et en respectant les personnes et la loi",
     ["Utiliser l'IA sans jamais reflechir", "Cacher qu'on utilise une IA en toute circonstance",
      "Confier toutes les decisions a la machine"], MOYEN, "La supervision humaine est au coeur de l'IA responsable."),
    ("Peut-on utiliser une image generee par IA sans aucune precaution commerciale ?",
     "Non, il faut verifier les conditions d'utilisation et les droits applicables",
     ["Oui, tout est toujours libre de droits", "Oui, si personne ne le remarque",
      "Oui, les images IA n'ont jamais de regles"], MOYEN, "Les conditions d'utilisation varient selon les outils."),
    ("Que risque une entreprise qui saisit des donnees confidentielles de clients dans un outil en ligne inconnu ?",
     "Une fuite de donnees et une perte de confiance",
     ["Un gain de temps sans risque", "Une meilleure securite",
      "Une exoneration de responsabilite"], MOYEN, "La confidentialite des donnees clients engage l'entreprise."),
    ("Qu'est-ce qu'un deepfake ?", "Une video ou un audio truque de facon realiste par intelligence artificielle",
     ["Un logiciel de comptabilite", "Un type de batterie", "Un reseau social"],
     MOYEN, "Le deepfake peut servir a desinformer ou a usurper une identite."),
    ("Comment reagir face a une video suspecte partagee sur les reseaux ?",
     "Verifier la source et croiser avec des medias fiables avant de partager",
     ["La partager immediatement", "La croire sans reflechir",
      "L'utiliser comme preuve officielle"], FACILE, "La verification limite la propagation de fausses informations."),
    ("Pourquoi les entreprises collectent-elles des donnees sur leurs clients ?",
     "Pour mieux comprendre les besoins et personnaliser leur offre",
     ["Pour les revendre systematiquement sans regle", "Pour les detruire",
      "Sans aucune raison"], MOYEN, "La donnee sert la connaissance client, dans un cadre respectueux."),
    ("Quel principe doit guider la collecte de donnees personnelles ?",
     "Ne collecter que ce qui est necessaire et informer les personnes",
     ["Collecter le maximum possible", "Collecter en secret",
      "Revendre sans consentement"], MOYEN, "Minimisation et transparence sont des principes de base."),
    ("Que designe la fracture numerique ?", "L'ecart entre ceux qui accedent au numerique et ceux qui en sont exclus",
     ["Un ecran casse", "Une panne de serveur", "Un virus informatique"],
     FACILE, "Elle concerne l'acces, l'equipement et les competences."),
    ("Quel facteur limite le plus l'usage d'internet en zone rurale africaine ?",
     "La couverture reseau et le cout des donnees",
     ["L'absence de langue locale", "L'interdiction legale d'internet",
      "Le manque d'ordinateurs de bureau uniquement"], MOYEN, "Couverture et cout restent les freins majeurs."),
    ("Pourquoi la formation est-elle indispensable a la transformation numerique d'une entreprise ?",
     "Parce qu'un outil non maitrise n'apporte aucun benefice",
     ["Parce que la loi l'oblige", "Parce que les outils fonctionnent seuls",
      "Parce que cela remplace la strategie"], FACILE, "L'appropriation par les equipes conditionne le resultat."),
    ("Quel est le point commun entre un chatbot, un traducteur automatique et un correcteur de texte ?",
     "Ils reposent tous sur le traitement automatique du langage",
     ["Ils fonctionnent tous sans electricite", "Ils sont tous interdits en entreprise",
      "Ils necessitent tous une imprimante"], MOYEN, "Ces trois usages relevent du traitement du langage naturel."),
    ("Pourquoi faut-il rediger une consigne claire quand on utilise une IA generative ?",
     "Parce que la qualite de la reponse depend directement de la precision de la demande",
     ["Parce que l'IA refuse les phrases courtes", "Parce que la loi impose un format",
      "Parce que l'IA ne lit que les majuscules"], FACILE, "Un prompt precis donne un resultat exploitable."),
    ("Une IA peut-elle remplacer le jugement d'un dirigeant sur une decision strategique ?",
     "Non, elle peut aider a analyser mais la decision reste humaine",
     ["Oui, elle decide mieux dans tous les cas", "Oui, elle connait l'avenir",
      "Oui, elle remplace le conseil d'administration"], MOYEN, "L'IA est une aide a la decision, pas un decideur."),
    ("Quel est le risque de confier des donnees clients a un outil en ligne sans lire ses conditions ?",
     "Perdre la maitrise de l'usage qui sera fait de ces donnees",
     ["Ameliorer automatiquement sa securite", "Obtenir une certification",
      "Reduire ses couts sans contrepartie"], MOYEN, "Les conditions d'utilisation determinent le sort des donnees."),
    ("Qu'est-ce qui distingue une invention d'une innovation ?",
     "L'invention est une idee ou un dispositif nouveau, l'innovation est son adoption reelle sur un marche",
     ["Il n'y a aucune difference", "L'innovation precede toujours l'invention",
      "L'invention exige un client, pas l'innovation"], CHALLENGE, "L'innovation suppose une adoption effective."),
    ("Pourquoi de nombreuses innovations echouent-elles malgre une bonne technologie ?",
     "Parce qu'elles ne repondent pas a un besoin reel ou ne sont pas adoptees",
     ["Parce que la technologie est toujours mauvaise", "Parce que les clients sont trop nombreux",
      "Parce que le prix est toujours trop bas"], MOYEN, "L'adoption par les utilisateurs decide du succes."),
    ("Quelle competence devient essentielle a l'ere de l'IA generative ?",
     "Savoir formuler une demande precise et verifier le resultat obtenu",
     ["Savoir taper vite au clavier uniquement", "Savoir reciter des codes",
      "Savoir eviter tout outil numerique"], MOYEN, "Formuler et verifier sont les deux competences cles."),
    ("Quel est le principal avantage d'un outil numerique bien choisi pour une petite equipe ?",
     "Gagner du temps sur les taches repetitives pour se concentrer sur le client",
     ["Multiplier les reunions", "Augmenter la paperasse",
      "Reduire le contact avec les clients"], FACILE, "L'outil doit liberer du temps a valeur ajoutee."),
    ("Comment mesurer si une innovation apporte reellement de la valeur a une entreprise ?",
     "En comparant les gains obtenus au cout total de sa mise en oeuvre",
     ["En comptant le nombre d'ecrans", "En comptant les articles de presse",
      "En comptant les reunions organisees"], MOYEN, "La valeur se mesure en gains nets."),
    ("Pourquoi un entrepreneur doit-il tester une technologie avant de la generaliser ?",
     "Pour verifier qu'elle fonctionne dans son contexte reel et qu'elle est adoptee",
     ["Pour retarder son projet", "Pour depenser davantage",
      "Pour eviter d'apprendre"], FACILE, "Le test en conditions reelles evite les mauvaises surprises."),
    ("Quel usage de l'IA reste deconseille sans verification humaine ?",
     "La production de documents juridiques ou medicaux engageants",
     ["La generation d'idees de brainstorming", "La reformulation d'un texte interne",
      "La creation d'un brouillon de publication"], MOYEN, "Plus l'enjeu est fort, plus la supervision est necessaire."),
    ("Que signifie le fait qu'un modele d'IA soit entraine sur des donnees anciennes ?",
     "Il peut ignorer les evenements et informations recents",
     ["Il est necessairement faux", "Il devient plus rapide",
      "Il connait l'avenir"], MOYEN, "La date de fin d'entrainement limite les connaissances du modele."),
    ("Quelle erreur frequente commettent les entreprises qui se digitalisent ?",
     "Acheter des outils sans revoir leurs processus ni former les equipes",
     ["Former trop leurs equipes", "Documenter trop leurs procedures",
      "Ecouter trop leurs clients"], MOYEN, "La technologie seule ne transforme rien."),
]


def build() -> list[Q]:
    qs: list[Q] = []
    realisations = [v[0] for v in PIONNIERS.values()]
    domaines = sorted({v[1] for v in PIONNIERS.values()})
    noms = list(PIONNIERS.keys())
    for nom, (realisation, domaine, diff) in PIONNIERS.items():
        qs.append(Q(
            f"Pour quelle contribution {nom} est-il ou est-elle connu(e) ?",
            realisation, others(nom, realisations), diff, "innovation,histoire",
            f"{nom} est associe(e) a {realisation}.",
        ))
        qs.append(Q(
            f"Qui est a l'origine de cette avancee : {realisation} ?",
            nom, others(realisation, noms), diff, "innovation,histoire",
            f"Il s'agit de {nom}.",
        ))
        qs.append(Q(
            f"Dans quel domaine {nom} a-t-il ou a-t-elle laisse sa marque ?",
            domaine, others(nom + "d", domaines), diff, "innovation,histoire",
            f"{nom} a marque ce domaine : {domaine}.",
        ))
    for question, correct, wrong, diff, expl in DATES:
        qs.append(Q(question, correct, wrong, diff, "innovation,histoire", expl))
    for question, correct, wrong, diff, expl in CULTURE:
        qs.append(Q(question, correct, wrong, diff, "innovation,comprehension", expl))
    return qs
