# -*- coding: utf-8 -*-
"""Banque Innovation & IA : glossaire accessible du numerique et de l'IA."""

from __future__ import annotations

from .common import cap, CHALLENGE, FACILE, MOYEN, Q, others

GLOSSAIRE = {
    "l'intelligence artificielle": ("Une technologie qui permet a une machine d'accomplir des taches demandant habituellement de l'intelligence humaine", FACILE),
    "un algorithme": ("Une suite d'instructions permettant de resoudre un probleme ou d'accomplir une tache", FACILE),
    "une donnee": ("Une information enregistree qui peut etre traitee par un ordinateur", FACILE),
    "une base de donnees": ("Un ensemble d'informations organisees pour etre retrouvees facilement", FACILE),
    "un chatbot": ("Un programme qui dialogue automatiquement avec les utilisateurs", FACILE),
    "un assistant vocal": ("Un service qui repond a des commandes prononcees a voix haute", FACILE),
    "l'apprentissage automatique": ("La capacite d'un programme a s'ameliorer a partir d'exemples", MOYEN),
    "l'IA generative": ("Une intelligence artificielle capable de produire du texte, des images ou du son", MOYEN),
    "un prompt": ("La consigne que l'on donne a une intelligence artificielle pour obtenir une reponse", MOYEN),
    "un modele de langage": ("Un systeme entraine sur de grands volumes de textes pour comprendre et produire du langage", CHALLENGE),
    "une hallucination d'IA": ("Une reponse inventee par l'IA mais presentee comme vraie", MOYEN),
    "un biais algorithmique": ("Une distorsion des resultats reproduisant des prejuges presents dans les donnees", MOYEN),
    "la reconnaissance vocale": ("La transformation automatique de la parole en texte", FACILE),
    "la reconnaissance faciale": ("L'identification d'une personne a partir de l'image de son visage", MOYEN),
    "la traduction automatique": ("La conversion d'un texte d'une langue a une autre par un logiciel", FACILE),
    "un systeme de recommandation": ("Un dispositif qui suggere des contenus ou produits selon les gouts de l'utilisateur", MOYEN),
    "l'automatisation": ("Le fait de confier a une machine une tache repetitive realisee auparavant a la main", FACILE),
    "la numerisation": ("Le passage d'un support papier ou manuel a un format numerique", FACILE),
    "la transformation digitale": ("La reorganisation d'une activite autour des outils numeriques", MOYEN),
    "le cloud": ("Le stockage et le traitement de donnees sur des serveurs accessibles par internet", MOYEN),
    "une sauvegarde": ("Une copie de securite des donnees permettant de les restaurer", FACILE),
    "un serveur": ("Un ordinateur qui fournit des services ou des donnees a d'autres appareils", MOYEN),
    "une application mobile": ("Un programme installe sur un telephone pour rendre un service", FACILE),
    "une application web": ("Un service utilisable directement depuis un navigateur, sans installation", MOYEN),
    "un navigateur": ("Le logiciel qui permet de consulter des sites internet", FACILE),
    "un moteur de recherche": ("Un service qui trouve des pages web a partir de mots-cles", FACILE),
    "un site web": ("Un ensemble de pages accessibles en ligne a une meme adresse", FACILE),
    "un nom de domaine": ("L'adresse unique qui identifie un site sur internet", MOYEN),
    "l'hebergement web": ("Le service qui stocke un site et le rend accessible en ligne", MOYEN),
    "un reseau social": ("Une plateforme permettant de publier et d'echanger avec une communaute", FACILE),
    "le e-commerce": ("La vente de produits ou services sur internet", FACILE),
    "une place de marche en ligne": ("Un site qui met en relation de nombreux vendeurs et acheteurs", MOYEN),
    "le mobile money": ("Un service permettant d'envoyer et de recevoir de l'argent depuis un telephone", FACILE),
    "un portefeuille electronique": ("Un compte numerique qui stocke de l'argent pour payer en ligne ou par telephone", MOYEN),
    "un code QR": ("Un carre imprime qui, une fois scanne, ouvre un lien ou une information", FACILE),
    "un lien hypertexte": ("Un element cliquable qui renvoie vers une autre page ou ressource", FACILE),
    "le wifi": ("Une technologie de connexion a internet sans fil sur une courte distance", FACILE),
    "la 4G": ("Une norme de reseau mobile permettant un acces rapide a internet", FACILE),
    "la fibre optique": ("Une technologie de cable permettant des debits internet tres eleves", MOYEN),
    "un mot de passe": ("Une suite secrete de caracteres qui protege l'acces a un compte", FACILE),
    "l'authentification a deux facteurs": ("Une securite qui demande un second element de verification en plus du mot de passe", MOYEN),
    "le phishing": ("Une tentative de vol d'informations en se faisant passer pour un organisme de confiance", MOYEN),
    "un virus informatique": ("Un programme malveillant qui se propage et endommage un systeme", FACILE),
    "un rancongiciel": ("Un logiciel malveillant qui bloque les donnees et reclame une rancon", CHALLENGE),
    "un pare-feu": ("Un dispositif qui filtre les connexions pour proteger un reseau", MOYEN),
    "le chiffrement": ("La transformation de donnees en un format illisible sans la cle appropriee", MOYEN),
    "les donnees personnelles": ("Les informations qui permettent d'identifier une personne", FACILE),
    "la vie privee numerique": ("La protection des informations personnelles dans les usages en ligne", FACILE),
    "un cookie": ("Un petit fichier depose par un site pour retenir des informations sur la visite", MOYEN),
    "le spam": ("Un message non sollicite envoye en masse", FACILE),
    "un objet connecte": ("Un appareil du quotidien relie a internet pour transmettre des informations", MOYEN),
    "un capteur": ("Un composant qui mesure une grandeur physique et la transmet", MOYEN),
    "un drone": ("Un aeronef sans pilote a bord, pilote a distance ou automatiquement", FACILE),
    "une imprimante 3D": ("Une machine qui fabrique un objet en deposant de la matiere couche par couche", MOYEN),
    "la realite virtuelle": ("Une technologie qui plonge l'utilisateur dans un environnement entierement simule", MOYEN),
    "la realite augmentee": ("Une technologie qui superpose des informations numeriques au monde reel", MOYEN),
    "un robot": ("Une machine programmable capable d'executer des taches physiques", FACILE),
    "la blockchain": ("Un registre numerique partage qui enregistre les transactions de facon infalsifiable", CHALLENGE),
    "une cryptomonnaie": ("Une monnaie numerique fonctionnant sans banque centrale", MOYEN),
    "le big data": ("Le traitement de volumes de donnees trop importants pour les outils classiques", MOYEN),
    "un tableau de bord numerique": ("Un ecran qui rassemble les indicateurs cles d'une activite", MOYEN),
    "une visioconference": ("Une reunion a distance avec image et son", FACILE),
    "le teletravail": ("Le fait de travailler a distance grace aux outils numeriques", FACILE),
    "le no-code": ("La creation d'applications sans ecrire de code informatique", MOYEN),
    "une API": ("Une interface qui permet a deux logiciels de communiquer entre eux", CHALLENGE),
    "un logiciel libre": ("Un logiciel dont le code peut etre utilise, modifie et partage librement", MOYEN),
    "une mise a jour": ("Une nouvelle version qui corrige ou ameliore un logiciel", FACILE),
    "un bug": ("Un defaut de fonctionnement dans un programme", FACILE),
    "la maintenance": ("L'entretien regulier d'un systeme pour qu'il reste operationnel", FACILE),
    "un utilisateur": ("La personne qui se sert d'un produit ou d'un service numerique", FACILE),
    "l'experience utilisateur": ("La qualite du ressenti d'une personne lorsqu'elle utilise un service", MOYEN),
    "l'interface": ("La partie visible d'un logiciel avec laquelle l'utilisateur interagit", MOYEN),
    "l'accessibilite numerique": ("La conception de services utilisables aussi par les personnes en situation de handicap", MOYEN),
    "la fracture numerique": ("L'ecart entre ceux qui ont acces au numerique et ceux qui en sont prives", MOYEN),
    "l'inclusion numerique": ("Les actions visant a permettre a tous d'utiliser les outils numeriques", MOYEN),
    "l'innovation": ("La mise en oeuvre concrete d'une idee nouvelle qui apporte de la valeur", FACILE),
    "l'innovation incrementale": ("Une amelioration progressive d'un produit ou service existant", MOYEN),
    "l'innovation de rupture": ("Une innovation qui bouleverse un marche et remplace les solutions existantes", MOYEN),
    "l'innovation frugale": ("Une innovation qui obtient un resultat utile avec des moyens tres limites", CHALLENGE),
    "l'innovation d'usage": ("Une nouvelle facon d'utiliser une technologie existante", CHALLENGE),
    "un brevet d'invention": ("Un titre qui protege une invention technique pendant une duree limitee", MOYEN),
    "la veille technologique": ("La surveillance organisee des evolutions techniques d'un secteur", MOYEN),
    "un ecosysteme numerique": ("L'ensemble des acteurs qui font vivre l'innovation d'un territoire", MOYEN),
    "un hackathon": ("Un evenement court ou des equipes concoivent une solution numerique", MOYEN),
    "un incubateur technologique": ("Une structure qui heberge et accompagne de jeunes entreprises innovantes", MOYEN),
    "un prototype numerique": ("Une premiere version testable d'un service numerique", MOYEN),
    "un test utilisateur": ("Une observation de personnes reelles utilisant le produit", MOYEN),
    "le pilotage par la donnee": ("La prise de decisions fondee sur des chiffres mesures plutot que sur l'intuition", CHALLENGE),
    "un indicateur numerique": ("Une mesure chiffree du fonctionnement d'un service en ligne", MOYEN),
    "le referencement": ("L'ensemble des techniques qui ameliorent la visibilite d'un site dans les recherches", MOYEN),
    "une newsletter": ("Un message d'information envoye regulierement a une liste d'abonnes", FACILE),
    "un tunnel de conversion": ("Le parcours qui mene un visiteur en ligne jusqu'a l'achat", CHALLENGE),
    "un avis client en ligne": ("Un commentaire public laisse par un acheteur sur un produit ou un service", FACILE),
    "la e-reputation": ("L'image d'une personne ou d'une entreprise telle qu'elle apparait sur internet", MOYEN),
    "un influenceur numerique": ("Une personne dont l'audience en ligne peut orienter les choix d'achat", FACILE),
    "la publicite ciblee": ("Une publicite adressee a un public selectionne selon ses caracteristiques", MOYEN),
    "un abonnement numerique": ("Un paiement recurrent donnant acces a un service en ligne", FACILE),
    "un logiciel de gestion": ("Un outil qui aide a suivre les stocks, les ventes ou la comptabilite", FACILE),
    "un tableur": ("Un logiciel qui organise des donnees en lignes et colonnes et effectue des calculs", FACILE),
    "un document partage": ("Un fichier consultable et modifiable a plusieurs en ligne", FACILE),
    "une signature electronique": ("Un procede qui authentifie un signataire sur un document numerique", MOYEN),
    "une facture electronique": ("Une facture emise, transmise et conservee sous format numerique", MOYEN),
    "un identifiant": ("Le nom d'utilisateur qui permet de se connecter a un service", FACILE),
    "la biometrie": ("L'identification d'une personne par une caracteristique physique unique", MOYEN),
    "le deepfake": ("Un contenu video ou audio truque de facon realiste par intelligence artificielle", MOYEN),
    "la desinformation en ligne": ("La diffusion volontaire d'informations fausses sur internet", FACILE),
    "la verification des sources": ("Le fait de controler l'origine d'une information avant de la croire", FACILE),
    "l'empreinte numerique": ("L'ensemble des traces laissees par une personne en ligne", MOYEN),
    "la sobriete numerique": ("La reduction de l'impact environnemental des usages numeriques", CHALLENGE),
    "le numerique responsable": ("Une approche qui limite les effets negatifs sociaux et ecologiques du numerique", CHALLENGE),
    "l'IA responsable": ("L'usage de l'intelligence artificielle dans le respect des personnes et de la loi", MOYEN),
    "la supervision humaine": ("Le controle par une personne des decisions proposees par une machine", MOYEN),
    "l'automatisation des taches administratives": ("Le traitement automatique de tache repetitives comme la saisie ou les relances", MOYEN),
    "un agent conversationnel de service client": ("Un robot qui repond aux questions frequentes des clients", MOYEN),
    "un logiciel de caisse": ("Un outil qui enregistre les ventes et edite les tickets", FACILE),
    "un code-barres": ("Une suite de barres lisible par un scanner pour identifier un produit", FACILE),
    "la geolocalisation": ("La determination de la position geographique d'un appareil", FACILE),
    "le GPS": ("Un systeme satellitaire qui indique une position et guide un deplacement", FACILE),
    "une carte numerique": ("Une representation geographique consultable en ligne", FACILE),
    "un service de livraison connecte": ("Une application qui organise et suit les livraisons en temps reel", MOYEN),
    "la telemedecine": ("La consultation medicale realisee a distance grace aux outils numeriques", MOYEN),
    "l'agriculture de precision": ("L'usage de donnees et de capteurs pour optimiser les cultures", CHALLENGE),
    "l'e-learning": ("La formation a distance via des supports numeriques", FACILE),
    "un MOOC": ("Un cours en ligne ouvert et accessible a un grand nombre de participants", MOYEN),
    "la cybersecurite": ("L'ensemble des moyens qui protegent les systemes et les donnees contre les attaques", FACILE),
    "une faille de securite": ("Une faiblesse d'un systeme qui peut etre exploitee par un attaquant", MOYEN),
    "une fuite de donnees": ("La divulgation non autorisee d'informations detenues par une organisation", MOYEN),
    "un audit numerique": ("L'examen des outils et pratiques numeriques d'une organisation", CHALLENGE),
    "un jumeau numerique": ("La copie virtuelle d'un objet ou d'un processus reel", CHALLENGE),
    "l'informatique en periphérie": ("Le traitement des donnees au plus pres de l'endroit ou elles sont produites", CHALLENGE),
    "un centre de donnees": ("Un batiment qui heberge des serveurs informatiques", MOYEN),
    "la bande passante": ("La quantite de donnees pouvant transiter par une connexion en un temps donne", CHALLENGE),
    "un forfait de donnees": ("Le volume d'internet mobile inclus dans un abonnement", FACILE),
    "un compte utilisateur": ("L'espace personnel cree pour acceder a un service en ligne", FACILE),
    "un profil en ligne": ("La page qui presente une personne ou une entreprise sur une plateforme", FACILE),
    "une publication": ("Un contenu diffuse sur un reseau social ou un site", FACILE),
    "un abonne": ("Une personne qui suit les publications d'un compte", FACILE),
    "un commentaire": ("Une reaction ecrite laissee sous une publication", FACILE),
    "un partage": ("La rediffusion d'un contenu vers son propre reseau", FACILE),
    "une story": ("Une publication ephemere qui disparait apres un temps limite", FACILE),
    "un hashtag": ("Un mot-cle precede d'un diese servant a classer les publications", FACILE),
    "une audience en ligne": ("L'ensemble des personnes touchees par un contenu numerique", MOYEN),
    "le taux d'engagement": ("La part de l'audience qui reagit a un contenu", CHALLENGE),
    "une campagne sponsorisee": ("Une publication payante diffusee a un public cible", MOYEN),
    "un pixel de suivi": ("Un petit element qui mesure le comportement des visiteurs d'un site", CHALLENGE),
    "une adresse IP": ("Le numero qui identifie un appareil connecte a un reseau", MOYEN),
    "un routeur": ("L'appareil qui distribue la connexion internet dans un local", MOYEN),
    "un modem": ("L'appareil qui relie un local au reseau de l'operateur", MOYEN),
    "un point d'acces mobile": ("Le partage de la connexion internet d'un telephone avec d'autres appareils", FACILE),
    "un SMS": ("Un message texte court envoye par le reseau telephonique", FACILE),
    "une notification push": ("Un message envoye par une application sur l'ecran du telephone", FACILE),
    "un systeme d'exploitation": ("Le logiciel de base qui fait fonctionner un ordinateur ou un telephone", MOYEN),
    "un fichier": ("Un ensemble de donnees enregistrees sous un nom", FACILE),
    "un dossier": ("Un espace de rangement qui regroupe des fichiers", FACILE),
    "un format de fichier": ("La maniere dont les donnees d'un fichier sont structurees", MOYEN),
    "un PDF": ("Un format de document qui conserve la mise en page a l'identique", FACILE),
    "la compression de fichier": ("La reduction de la taille d'un fichier pour l'envoyer plus facilement", MOYEN),
    "une piece jointe": ("Un fichier envoye avec un message electronique", FACILE),
    "un espace disque": ("La capacite de stockage disponible sur un appareil", FACILE),
    "la memoire vive": ("La memoire de travail temporaire d'un appareil", CHALLENGE),
    "un processeur": ("Le composant qui execute les calculs d'un appareil", MOYEN),
    "une carte graphique": ("Le composant specialise dans le traitement des images", CHALLENGE),
    "un ordinateur portable": ("Un ordinateur autonome et transportable", FACILE),
    "une tablette": ("Un appareil tactile intermediaire entre le telephone et l'ordinateur", FACILE),
    "un ecran tactile": ("Un ecran qui reagit directement au contact du doigt", FACILE),
    "un peripherique": ("Un appareil externe relie a un ordinateur", MOYEN),
    "un scanner": ("Un appareil qui transforme un document papier en fichier numerique", FACILE),
    "un videoprojecteur": ("Un appareil qui affiche une image sur un grand ecran ou un mur", FACILE),
    "un lecteur de code-barres": ("Un appareil qui lit automatiquement l'identifiant d'un produit", MOYEN),
    "un terminal de paiement": ("L'appareil qui permet d'encaisser un paiement par carte", MOYEN),
    "une carte SIM": ("La puce qui identifie un abonne sur un reseau mobile", FACILE),
    "un identifiant unique": ("Un code qui distingue un element de tous les autres dans un systeme", MOYEN),
    "une plateforme numerique": ("Un service en ligne qui met en relation plusieurs types d'utilisateurs", MOYEN),
    "un marketplace": ("Une plateforme ou de nombreux vendeurs proposent leurs produits", MOYEN),
    "un service a la demande": ("Un service commande et obtenu immediatement via une application", MOYEN),
    "l'economie collaborative": ("Un modele ou des particuliers partagent biens et services via des plateformes", MOYEN),
    "un modele freemium": ("Une offre de base gratuite completee par des options payantes", CHALLENGE),
    "un abonnement mensuel": ("Un paiement recurrent qui donne acces a un service", FACILE),
    "un essai gratuit": ("Une periode ou le service est accessible sans payer, pour le tester", FACILE),
    "un support technique": ("L'assistance apportee aux utilisateurs en cas de probleme", FACILE),
    "une documentation utilisateur": ("Le guide expliquant comment utiliser un outil", MOYEN),
    "un tutoriel": ("Un contenu qui explique pas a pas comment realiser une tache", FACILE),
    "une communaute en ligne": ("Un groupe de personnes reunies autour d'un interet commun sur internet", FACILE),
    "un forum": ("Un espace en ligne d'echange de questions et de reponses", FACILE),
    "un moderateur": ("La personne qui veille au respect des regles dans un espace en ligne", MOYEN),
    "le cyberharcelement": ("Le harcelement d'une personne au moyen des outils numeriques", FACILE),
    "l'usurpation d'identite": ("Le fait de se faire passer pour quelqu'un d'autre", MOYEN),
    "une arnaque en ligne": ("Une tromperie visant a soutirer de l'argent ou des informations sur internet", FACILE),
    "un faux profil": ("Un compte cree sous une fausse identite", FACILE),
    "un site frauduleux": ("Un site imitant un service legitime pour tromper les visiteurs", MOYEN),
    "la double authentification": ("Une securite exigeant deux preuves d'identite differentes", MOYEN),
    "un code a usage unique": ("Un code valable une seule fois pour valider une operation", MOYEN),
    "une politique de confidentialite": ("Le document expliquant comment un service traite les donnees personnelles", MOYEN),
    "des conditions generales d'utilisation": ("Les regles qui encadrent l'usage d'un service en ligne", MOYEN),
    "le consentement": ("L'accord libre et informe donne avant l'utilisation de ses donnees", MOYEN),
    "l'anonymisation": ("La suppression des elements permettant d'identifier une personne dans un jeu de donnees", CHALLENGE),
    "un jeu de donnees": ("Un ensemble structure de donnees utilise pour analyser ou entrainer un modele", MOYEN),
    "l'entrainement d'un modele": ("La phase pendant laquelle un systeme d'IA apprend a partir de donnees", CHALLENGE),
    "l'annotation de donnees": ("Le fait d'etiqueter des donnees pour apprendre a une IA a les reconnaitre", CHALLENGE),
    "la classification automatique": ("Le tri automatique d'elements dans des categories predefinies", CHALLENGE),
    "la prediction": ("L'estimation d'une valeur future a partir de donnees passees", MOYEN),
    "la vision par ordinateur": ("La capacite d'un systeme a interpreter des images", CHALLENGE),
    "le traitement du langage naturel": ("La capacite d'un systeme a analyser et produire du langage humain", CHALLENGE),
    "la synthese vocale": ("La transformation d'un texte en parole audible", MOYEN),
    "la generation d'images": ("La creation d'images nouvelles par un modele d'intelligence artificielle", MOYEN),
    "un filtre anti-spam": ("Un dispositif qui ecarte automatiquement les messages indesirables", FACILE),
    "un correcteur automatique": ("Un outil qui detecte et corrige les fautes dans un texte", FACILE),
    "un moteur de traduction": ("Un systeme qui convertit automatiquement un texte d'une langue a une autre", FACILE),
    "un resume automatique": ("La production par une machine d'une version courte d'un texte long", MOYEN),
    "la personnalisation": ("L'adaptation d'un service aux preferences de chaque utilisateur", MOYEN),
    "un profil utilisateur": ("L'ensemble des informations et preferences associees a une personne", MOYEN),
    "l'historique de navigation": ("La liste des pages consultees par un utilisateur", FACILE),
    "un mode hors ligne": ("La possibilite d'utiliser un service sans connexion internet", MOYEN),
    "la synchronisation": ("La mise a jour automatique des memes donnees sur plusieurs appareils", MOYEN),
    "un identifiant de transaction": ("Le code qui permet de retrouver une operation de paiement", MOYEN),
    "un recu electronique": ("La preuve de paiement transmise sous forme numerique", FACILE),
    "un devis en ligne": ("Une proposition de prix transmise par un canal numerique", FACILE),
    "un paiement fractionne": ("Un reglement reparti en plusieurs echeances", MOYEN),
    "un remboursement en ligne": ("Le retour d'une somme au client via un canal numerique", MOYEN),
    "un panier d'achat": ("L'espace qui rassemble les produits selectionnes avant le paiement", FACILE),
    "un abandon de panier": ("Le fait de quitter un site sans finaliser sa commande", MOYEN),
    "un code promotionnel": ("Une suite de caracteres donnant droit a une reduction en ligne", FACILE),
    "un programme de fidelite numerique": ("Un dispositif qui recompense les achats repetes via une application", MOYEN),
    "un service apres-vente en ligne": ("L'assistance au client apres l'achat, par des canaux numeriques", FACILE),
    "un chatbot de support": ("Un robot qui traite les demandes courantes des clients", MOYEN),
    "un ticket d'assistance": ("La demande enregistree d'un utilisateur aupres du support", MOYEN),
    "un temps de reponse": ("Le delai entre la demande d'un utilisateur et la reponse recue", FACILE),
    "un taux de disponibilite": ("La proportion de temps pendant laquelle un service fonctionne", CHALLENGE),
    "une panne de service": ("L'interruption temporaire d'un service numerique", FACILE),
    "un plan de continuite": ("L'organisation prevue pour maintenir l'activite malgre un incident", CHALLENGE),
    "la redondance": ("Le fait de dupliquer un equipement ou une donnee pour eviter une interruption", CHALLENGE),
    "un test de charge": ("Une verification du comportement d'un service face a un grand nombre d'utilisateurs", CHALLENGE),
    "une version beta": ("Une version d'essai diffusee avant la sortie officielle", MOYEN),
    "un retour utilisateur": ("L'avis exprime par une personne apres avoir utilise un service", FACILE),
    "une feuille de route produit": ("Le plan des evolutions prevues pour un service numerique", CHALLENGE),
    "un cahier des charges numerique": ("Le document decrivant precisement les fonctions attendues d'un outil", MOYEN),
    "un prestataire informatique": ("Une entreprise externe chargee de realiser ou maintenir un service numerique", MOYEN),
    "un contrat de maintenance": ("L'accord qui organise l'entretien et le depannage d'un systeme", MOYEN),
}


def build() -> list[Q]:
    qs: list[Q] = []
    definitions = [v[0] for v in GLOSSAIRE.values()]
    termes = list(GLOSSAIRE.keys())
    for terme, (definition, diff) in GLOSSAIRE.items():
        qs.append(Q(
            f"Dans le monde numerique, que designe {terme} ?",
            definition, others(terme, definitions), diff, "innovation,glossaire",
            f"{cap(terme)} : {definition.lower()}.",
        ))
        qs.append(Q(
            f"Quel terme correspond a cette definition : {definition} ?",
            terme, others(definition, termes), diff, "innovation,glossaire",
            f"Il s'agit de {terme}.",
        ))
    return qs
